### ISSUE TITLE
Create Menu for Recall/Rehearse/Quit

### ISSUE THREAD

**Issue by michaelmendoza** [reputage/seedQuest#139]
Create a UI for Recall/Rehearse/Quit to appear in the starting scene right after clicking any button to start.

**Comment by michaelmendoza** [comment]
Using this as a template for the UI

<img width="856" alt="screen shot 2018-07-20 at 5 06 57 pm" src="https://user-images.githubusercontent.com/4431065/43028819-5a15c57e-8c3f-11e8-8803-3637c5d9b2e2.png">

**Comment by westonb7** [comment]
![screen shot 2018-07-23 at 12 03 27 pm](https://user-images.githubusercontent.com/30869523/43094592-99f4fca4-8e70-11e8-837e-4268d1c28510.png)

**Comment by michaelmendoza** [comment]
Looks good!
