### ISSUE TITLE
Fix ActionDisplay(Objectives)

### ISSUE THREAD

**Issue by michaelmendoza** [reputage/seedQuest#140]
Make ActionDisplay fully dynamic based on data from interactables path

**Comment by michaelmendoza** [comment]
<img width="306" alt="screen shot 2018-07-20 at 5 18 58 pm" src="https://user-images.githubusercontent.com/4431065/43029096-06e4dff0-8c41-11e8-8e46-c5bca4b281b4.png">

**Comment by westonb7** [comment]
![screen shot 2018-07-23 at 10 54 55 am](https://user-images.githubusercontent.com/30869523/43091333-0b382abc-8e67-11e8-9e4c-e410a3e3b685.png)
checkboxes are working now

**Comment by michaelmendoza** [comment]
Oh, I believe they were working before. You just needed to the new assets I was using for them. Did you install the package I gave you on Friday?

**Comment by michaelmendoza** [comment]
I am using a free third party library for some of the UI. It's called 'Simple UI'. You can find it in the unity store. If you didn't import the asset package I transferred from the flash drive.

**Comment by westonb7** [comment]
I imported the assets you gave me, but it still wasn't working. I'll look for the asset you mentioned.

**Comment by michaelmendoza** [comment]
It's possible it since we ran the code at some point before we imported that asset package that it lost the references to the images. They are set in the GameObject scriptable object, and you may just need to reconnect them.

**Comment by westonb7** [comment]
![screen shot 2018-07-23 at 1 24 01 pm](https://user-images.githubusercontent.com/30869523/43098411-6117f056-8e7c-11e8-82c7-d308723d707e.png)
Using the SimpleUI assets now
