### ISSUE TITLE
Tutorial Prompt or Walkthrough Video

### ISSUE THREAD

**Issue by michaelmendoza** [reputage/seedQuest#230]
Add a tutorial prompting system or a create a tutorial video on how to play using SeedQuestSandbox

**Comment by jasukim** [comment]
Here are the Tutorial UI Examples. Background is a a dark gray image at 45% Opacity and Layer Style is set to Multiply on Photoshop, not sure how that can be achieved in Unity. Basically it's adding Gray color to the background image, compounding the color as opposed to making it more opaque.


![tutorial_01](https://user-images.githubusercontent.com/6446247/52829521-ffadb780-3081-11e9-9f22-ab2e7c094a67.jpg)
![tutorial_02](https://user-images.githubusercontent.com/6446247/52829522-ffadb780-3081-11e9-85f0-f14b222442d3.jpg)
![tutorial_03](https://user-images.githubusercontent.com/6446247/52829523-ffadb780-3081-11e9-97bf-f8bec6f2cef3.jpg)

**Comment by jasukim** [comment]
I decided to make the header separate from the body of the popup to allow for better scaling in Unity. Scaling of the popup window should be Height and the Width should stay the same. (850px in my 1920 x 1280 screenshot)

![tutorial_ui_popup_header](https://user-images.githubusercontent.com/6446247/52830964-9e88e280-3087-11e9-9536-46d39c94ead9.png)
![tutorial_ui_popup_body](https://user-images.githubusercontent.com/6446247/52830967-9fba0f80-3087-11e9-9ea2-8df0ea761f8b.png)
![tutorial_ui_popup_button](https://user-images.githubusercontent.com/6446247/52830970-a183d300-3087-11e9-9113-fbae56c75a07.png)

**Comment by jasukim** [comment]
An arrow UI for pointing at things in HUD
![tutorial_ui_arrow](https://user-images.githubusercontent.com/6446247/52831348-32a77980-3089-11e9-86a8-62eecc370d10.png)

**Comment by jasukim** [comment]
Copied from above: Background is a a dark gray image at 45% Opacity and Layer Style is set to Multiply on Photoshop, not sure how that can be achieved in Unity. Basically it's adding Gray color to the background image, compounding the color as opposed to making it more opaque.

![tutorial_ui_bg](https://user-images.githubusercontent.com/6446247/52831519-c8db9f80-3089-11e9-8e15-48fd603196a3.png)

**Comment by jasukim** [comment]
I've included the text for Flatlands and Mindpalace practice mode as well as an optional Text pop up for Recall. Some of these might sound redundant, but there are subtle differences. I will also upload IMGs and videos sometime soon as well. 

[FlatLandsPractice.txt](https://github.com/reputage/seedQuest/files/2891825/FlatLandsPractice.txt)
[MindPalacePractice.txt](https://github.com/reputage/seedQuest/files/2891826/MindPalacePractice.txt)
[RecallMode.txt](https://github.com/reputage/seedQuest/files/2891827/RecallMode.txt)

**Comment by michaelmendoza** [comment]
Tutorials Added!

**Comment by trentlarson** [comment]
Where are the tutorials?  (We'd love to see a video or walk-through to show off.)

**Comment by ntelfer** [comment]
@trentlarson The tutorial was an in game walk through that existed in an earlier prototype of SeedQuest.  We will be adding a tutorial to the final version of seedQuest, unfortunately it doesn't exist in the current release. I've created task #392 to add it in again if you want to follow that for updates.

@michaelmendoza Do we have a updated video of the newest version that Trent can show off?

**Comment by michaelmendoza** [comment]
@trentlarson Here's a video of me playing through learn mode for SeedQuest:
https://drive.google.com/file/d/1KGQVR74GVLPtqJNTagBEr3vMhYIMSqjg/view?usp=sharing

Does that work for you?
We'll work on re-introducing the tutorials

**Comment by trentlarson** [comment]
That is PERFECT.  Thank you!  We'll show it off tomorrow, so I appreciate the response.
