### ISSUE TITLE
Command line console design

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#233]
On the front end: 
A canvas with an area to display previous commands
An input field for the user to type in commands
An attached monobehavior script should have keypress event listeners for activating the console command input field (the '~' key in Skyrim) and for entering the command (the 'enter' or 'return' key)
On activating the command line, the rest of the game should probably be paused (using PauseManager.isPaused() )

On the back end:
Input field text gets passed to a parsing function
Parsing function checks a hash map to see if the text matches a known command (such as 'help', setGameMode', etc)
Value from hash map determines which functions are called/what variables are changed
If command is not found, either a message is printed to the command history display, or nothing happens

Related to issue #229

**Comment by michaelmendoza** [comment]
Sounds good. Can you outline the class and functions you should build for this functionality before you start building the code?

**Comment by westonb7** [comment]
Yes - the front end should be simple, and on the back end I think it might work to make a class that contains a dictionary where the keys are strings for possible commands, and the values are function calls for those commands. Function calls in this dictionary can return a string with text to be printed onto the in-game console log. If this doesn't seem like a good way to build this feature, let me know and I'll build it differently

Front end:
Monobehavior script attached to empty gameobject with input field child object

void Start() { 
  get gameobject reference to input field object 
  get gameobject reference to rectangular area displaying previous commands / console output
}

void Update(){
  key event listener for backquote key
    on key down: activate input field object, and pause game
  key event listener for enter key
    on key down: get inputfield.text(), call parseInputCommand(string text)
}

public void parseInputCommand(string text){
  text.tolower();
  string[] textArray = text.Split(null);
  printToConsole( ConsoleCommandFunctions.execute(textArray[0], textArray[1]) )
}

public void printToConsole(string text){
  print out the 'text' string to the in-game console object
}

On the backend

static public class ConsoleCommandFunctions

public Dictionary<string, function> commands = new dictionary <string, functions>();
public Dictionary<string, string> helpInformation

public void initialize(){
  commands.Add("help", help);
  commands.Add("other", otherFunction)
}

public string execute(string command, string parameterText)
{
  return commands[command](parameterText);
}

// Example of a possible console command 
public string help(string helpQuery)
{
  string helpTextOutput = helpInformation(helpQuery);
  return helpTextOutput;
}

public string otherFunction(string text){
  // perform some function
  return text;
}

**Comment by westonb7** [comment]
Classes needed:

CommandInput (monobehavior class)
ConsoleCommandFunctions(public static class)

Functions needed:

CommandInput:
Start()
Update()
parseInputCommand()
printToConsole()

ConsoleCommandFunctions:
help()
toggleGameState()
setSeed()
printSeed()
changeScene()
showColliders()
setPlayerPosition()
restart()
etc...

**Comment by michaelmendoza** [comment]
Looks good. Just so you know in C# the way you use fuctions in a dictionary or as an input into a arg in a function is to use Delegate functions such as Action <T> or Func<T>. Func<T> is used if your delegate needs a return value, and Action<T> is if you don't need a return value. 

Only comment is I would name your CommandInput class to be CommandLineInputUI, ConsoleCommandFunctions to be CommandLineFunctions. Just to keep naming consistent and then make sure you place your function in the scripts/HUD folder inside the SeedQuestSandbox.

**Comment by westonb7** [comment]
Sounds good to me - I'll use the naming conventions you suggested when I start building it
