### ISSUE TITLE
Add support for multiple private keys

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#235]
One of the main purposes of SeedQuest is to allow a user to store multiple private keys using a single seed.  

With the current implementation at least on the user interface side they enter in a single private key, and after playing the game SeedQuest recovers and displays a single private key from Didery.

We need to add the following:

- [ ] Ask the user to give the key a name to identify it

- [ ] Put private key data in a json format before otp encrypting it.  Use the key name as the json key

- [ ] Validate the key name doesn't clobber existing private keys in Didery

- [ ] Create a user interface to display all private keys stored on Didery so a user can pick which ones they need

Eventually if we have a tight integration with other platforms we could potentially label the private keys for the user.

**Comment by westonb7** [comment]
Seedquest is no longer using Didery to store seeds.
