### ISSUE TITLE
Add backend support for seeds larger than 128 bits

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#238]

**Comment by michaelmendoza** [comment]
I would start off with 256 bits if you are going to do this

**Comment by westonb7** [comment]
Seeds can now be larger than 128 bits. Updated seed to byte tests to include tests for seeds up to 512 bits in size, and all tests of seeds sized 10 to 512 bits pass. Changes are in the 'console-commands' branch (I should have made a new branch for this change but I didn't think about it until it was too late, whoops). Changes were made in the seedquest-sandbox project, have not implemented them in the original seedquest project.
