### ISSUE TITLE
There is no way to exit the game

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#241]
**Description**
The controls menu says that you can hit esc to exit but pressing esc doesn't do anything.

**Setup**
OS: Windows
Affects: all prototypes

**Steps**

1. press esc

**Expected Results**
A confirm window pops up asking if they want to exit

**Actual Results**
Nothing happens

**Comment by michaelmendoza** [comment]
![image](https://user-images.githubusercontent.com/4431065/54227978-be64c800-44c6-11e9-9e0c-11e3cabb0bdc.png)

Added Menu to exit game
