### ISSUE TITLE
Memory lab: clicking on door does nothing

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#242]
**Describe the bug**
When prompted to click on the door after the first area in the memory lab, clicking on the door does nothing, preventing progress. Bug was found on the Mac build.

**To Reproduce**
Play through memory lab until prompted to click on door.

**Expected behavior**
Clicking on the door should do something

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: 2019_03_06_v1

**Additional context**
Probably a bounding box problem

**Comment by cameronthughes** [comment]
Doors removed.
