### ISSUE TITLE
Flatlands: tutorial begins again from the beginning in the second level

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#243]
**Describe the bug**
Tutorial pops up again when entering the second level of the flatlands

**To Reproduce**
Play through flatlands until you reach the second level.

**Expected behavior**
Tutorial probably shouldn't pop up again

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: 2019_03_06_v1

**Additional context**
.

**Comment by michaelmendoza** [comment]
Fixed
