### ISSUE TITLE
Flatlands: hovering blue arrow prevents clicking on the checkbox

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#244]
**Describe the bug**
The checkbox can still be clicked, just not when the hovering blue arrow is in front of it.

**To Reproduce**
Play through flatlands, try clicking on checkbox while the blue arrow is in front of the box.

**Expected behavior**
Check box should be clickable while the blue arrow is in front of it.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: 2019_03_06_v1

**Additional context**
.

**Comment by jasukim** [comment]
@michaelmendoza I noticed this bug too, is it possible to have the checkmark have priority when a User clicks on it? Or disable whatever it is in the Interactable Tracker that's blocking the checkmark?

**Comment by michaelmendoza** [comment]
Fixed
