### ISSUE TITLE
Endgame UI: prototype select button required clicking multiple times 

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#245]
**Describe the bug**
Prototype select button doesn't do anything right away, requires clicking multiple times. Button color didn't change on hover either, so it may not have loaded right away.

**To Reproduce**
Play through one of the prototypes until the endgame UI is reached, try clicking on the 'Prototype select' button immediately.

**Expected behavior**
Button should work the first time it's clicked on

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: 2019_03_06_v1

**Additional context**
.

**Comment by michaelmendoza** [comment]
This is because the scene is loading. There is no UI indication of loading. Should add one

**Comment by michaelmendoza** [comment]
Fixed for V0.0.11. Added LoadingScreen for PrototypeSelect
