### ISSUE TITLE
Command line function: show bounding boxes

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#246]
Create function that shows bounding boxes on interactables. I'm not sure how to show bounding boxes through scripting, but apparently requires adding a component to every interactable that enables an 'on gizmo draw' function.

**Comment by michaelmendoza** [comment]
![image (1)](https://user-images.githubusercontent.com/4431065/54068162-e6260880-4206-11e9-89e1-ecbf9d5e3b5b.png)

**Comment by michaelmendoza** [comment]
In CLI, type: showcolliders to see interactable box colliders
