### ISSUE TITLE
Mouse Doesn't Function When Moving

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#249]
**Description**
When you are moving with the wasd keys you cannot use your mouse to look around, or click on anything.

**To Reproduce**
1. Go to SeedQuest prototype
2. Start moving around the map
3. Try to look around while moving or click on an interactable

**Expected Behavior**
You can look around while moving

**Actual Behavior**
The mouse doesn't work while moving

**Device Info (please complete the following information):**
 - OS: Windows

**Comment by michaelmendoza** [comment]
@ntelfer Tried in Windows 10. Couldn't replicate it. Were you using a pad or a mouse?

**Comment by ntelfer** [comment]
Track pad on my laptop.
