### ISSUE TITLE
Flatlands/MindPalace: Highlight selection does not effect entire object

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#250]
**Description**
During Rehearsal mode, the next interactable special shader will only highlight a part of the interactable instead of the whole interactable. 

**To Reproduce**
1. In Flatlands, play through interactables. 
2. Come across an interactable (Poker Player/Table Cloth) where the highlight is only showing a part of the object. 

**Expected Behavior**
In Rehearsal Mode, user will find the next item and the interactable glowing shader would affect the main object instead of just a part. 

**Actual Behavior**
Only just a part of object has the highlight.

**Screenshots**
![image](https://user-images.githubusercontent.com/6446247/53920702-d8179280-4022-11e9-9063-8bc78b69bf19.png)

**Device Info (please complete the following information):**
 - OS: Windows 10
 - Version 2019_03_06_v1

**Comment by michaelmendoza** [comment]
![image](https://user-images.githubusercontent.com/4431065/54221932-03cec880-44ba-11e9-9c0e-d48424c0bdee.png)

Fixed!
