### ISSUE TITLE
Interactable Selection Doesn't Work If There Is An Interactable Behind It

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#251]
**Setup**
This requires a seed that uses tree in SeedQuest prototype

**To Reproduce**
1. Go to SeedQuest prototype learn mode
2. Select the Tree Till the Check appears
3. Adjust player so the tent is behind the check
4. Click the Check

**Expected Behavior**
The Check registers the click and the game action is recorded

**Actual Behavior**
The tent gets clicked and the tree selection isn't recorded.

**Device Info (please complete the following information):**
 - OS: Windows
 - Version: 2019_03_06_V1

**Comment by cameronthughes** [comment]
Adjusted box colliders and spaced out objects to prevent the accidental click.
