### ISSUE TITLE
MindPalace: Missing Amplify shaders cause broken materials

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#252]
**Description**
Build related, there seems to be missing Amplify shaders that is causing amplify materials to not show up in MindPalace>Campgrounds scene.

**To Reproduce**
1. Play MindPalace Prototype
2. Play through Nonna's Restaurant Level
3. Select Campgrounds Level on Level Select
4. Look towards right and you'll see magenta missing shaders on the water and car window. 

**Expected Behavior**
Water shader and car glass shader is working without bright pink missing shaders. 

**Actual Behavior**
Bright pink missing shader texture on water and car window.

**Screenshots**
![image](https://user-images.githubusercontent.com/6446247/53921149-4d379780-4024-11e9-909a-8f309a1c1f72.png)

**Device Info (please complete the following information):**
 - OS: Windows 10
 - Version 2019_03_06_v1

**Comment by michaelmendoza** [comment]
Fixed
