### ISSUE TITLE
Flatlands: Can't select Host Interactable 

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#253]
**Description**
In Flatlands>Nonna Restaurant, it is difficult to select the Host Interactable. 

**To Reproduce**
1. Play Flatlands Prototype, Learn mode
2. Play Nonna Restaurant where you have Host as part of your Next Item
3. Try to select on host

**Expected Behavior**
Expected that host will switch between items upon selecting the general area/body 

**Actual Behavior**
Very difficult to select Host, have to select above his head.

**Device Info (please complete the following information):**
 - OS: Win 10
 - Version: 2019_03_06_V1

**Comment by michaelmendoza** [comment]
Fixed Interactable BoundingBox

**Comment by michaelmendoza** [comment]
![image](https://user-images.githubusercontent.com/4431065/54468310-c9cb2400-4750-11e9-9e81-5c8a1ac878ee.png)
