### ISSUE TITLE
Laboratory: Door interactable needs to be removed as an interactable

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#254]
**Description**
Following up with bug meeting yesterday and playtesting Laboratory for myself, the door interactable will need to have a trigger instead to open it instead of using an interactable system to open the door, as it blocks users from progressing further. 

**To Reproduce**
1. Go to Memory Laboratory prototype, Learn Mode
2. Select interactables until you reach any of the door interactables as your next item
3. Try clicking it 
4. No selection box appears

**Expected Behavior**
Doors just open when close enough. (Or, have doors be a proper interactable choice in the original intent?)

**Actual Behavior**
When it is the Next Item interactable, doors do not have check mark above when needed or will not have the option to change to specific item variant, thus blocking user from progressing.

**Screenshots**
![image](https://user-images.githubusercontent.com/6446247/53922604-e1f0c400-4029-11e9-852c-791e1aecbc3a.png)

**Device Info (please complete the following information):**
 - OS: Win 10 x64
 - Version: 2019_03_06_V1

**Comment by cameronthughes** [comment]
Doors removed. Animations will be added later.
