### ISSUE TITLE
Cliffsides - can't click check box for the interactable with the sword and the skull

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#255]
**Description**
In the Cliffsides prototype, cannot click the checkbox for the sword and skull interactable. The arrows can be clicked to change the interactable, but the checkbox can't be clicked.

**To Reproduce**
Choose the Cliffsides prototype, and play until prompted to use the sword and skull interactable. This bug was encountered while playing Cliffsides after playing and completing learn mode for the SeedQuest prototype

**Expected Behavior**
Clicking the checkbox should act normally.

**Actual Behavior**
Clicking the checkbox just continues to change the interactable as if the arrows were clicked. This prevents progression in learn mode beyond this interactable.
 
**Device Info (please complete the following information):**
 - Mac
- version 2019_03_06_v1

**Comment by cameronthughes** [comment]
Moved collider back. During testing it worked fine.
