### ISSUE TITLE
Flatlands: preview shows the wrong color for the next interactable in learn mode

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#256]
**Description**
While playing the Flatlands prototype, in the second level (Nonna's restaurant) the wrong color is displayed for the next interactable. Preview works normally in the first level (saloon).

**To Reproduce**
Play the Flatlands prototype in learn mode, and play through until you reach the second level (Nonna's restaurant).

**Expected Behavior**
Preview shows the interactable in the color/state it's supposed to be changed to.

**Actual Behavior**
Preview shows the interactable in the default color/state. The correct interactable is displayed, just the wrong state.

**Device Info (please complete the following information):**
- Mac
- version 2019_03_06_v1

**Comment by michaelmendoza** [comment]
@westonb7  Can you show a screenshot?

**Comment by westonb7** [comment]
<img width="197" alt="Screen Shot 2019-03-11 at 1 05 27 PM" src="https://user-images.githubusercontent.com/30869523/54150773-edb00200-43fe-11e9-84dc-4e4ddfc029d6.png">

**Comment by michaelmendoza** [comment]
Fixed
