### ISSUE TITLE
Survey UI: SeedQuest prototypes quits before the survey data can be sent to the server

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#259]
**Description**
The application quits as soon as the 'submit' button is pressed, which most likely will cause survey responses to not be sent to the server. Could be fixed either by waiting for the coroutine to return before calling Application.quit(), or having an extra message pop up saying something like "thank you for your responses", to allow enough time for the data to be sent before quitting the application.

Not related to actual gameplay.

**Device Info (please complete the following information):**
Only tested on Mac, but will probably have the same problem on all platforms.

**Comment by michaelmendoza** [comment]
@BradyHammond Did you fix this?

**Comment by westonb7** [comment]
There does seem to be a delay in the application quitting now, but the data doesn't seem to be sent to the server. Current responses can be seen here: http://178.128.0.208:8000/surveys

**Comment by westonb7** [comment]
There's a few problems involved with sending data to the remote server: application.quit() can't be called by the coroutine sending the data, or else the data won't be sent. This is not a problem when sending responses in the unity editor, but in a build it is a problem. This has been changed in the '_survey-debugging_' branch. Unfortunately this causes the end screen of the survey to look odd, because it looks like nothing happens when the `submit` button is clicked.

Another problem is that the survey server won't accept post requests where the body is longer than 1000 characters (see issue #305 ). By default, the body being sent to the server with empty responses for all questions was around 2000. I've cut down the size of the post body to help with this, but unfortunately it also means that the open-ended questions have to be restricted to a certain number of characters to keep the body under 1000 characters. I can revert these changes if the server accepts longer post bodies.

**Comment by ntelfer** [comment]
Weston there's no need to change the SeedQuest side of the survey. This sounds like a configuration issue with the server. I'll look into it on Monday.

**Comment by westonb7** [comment]
With Nick's help the problem with sending data to the server is resolved. Turns out Unity by default  sets a header that we don't want. With this change, sending data and closing the application using Application.Quit works just fine now.

**Comment by michaelmendoza** [comment]
Sweet!
