### ISSUE TITLE
Alter How Recovered Seed Is Validated

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#260]
Currently we are using the decrypted key to sign data and then validating the signature matches the public key. This only works if the key is an eddsa key.  We need to find something that will work for any key. 

I think the best work around for now is to store the data in a json format before encrypting it. Then when a user recovers their seed we decrypt the data and if it comes out as valid json they probably recovered the seed correctly.

This does not guarantee the recovery was correct, but the chances of recovering an incorrect seed that also decrypts the data to valid json is unlikely.  We could also append some metadata to the json like the  number of entries as well to further reduce the likelihood of this happening. Something like this:
```json
{
    "some_label": "somekeyaldjfonownevoawienvowe=",
    "metadata": {
        "entries": 1
    }
}
```

This gives us some known key value pairs that we can do additional validation on to ensure there wasn't a freak accident where an incorrect seed decrypted valid json.

**Comment by ntelfer** [comment]
You could also add a hash to the metadata. This probably the best metadata to include.

**Comment by ntelfer** [comment]
Another solution is to generate a public key using the users seed and store that in the metadata.  Then to validate you generate a public key with the recovered seed and see if it matches the metadata key.

**Comment by westonb7** [comment]
Keys are no longer being used - only the seeds themselves, and do not require validation.
