### ISSUE TITLE
Add BIP-39 Integration

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#262]
We need to find a C# library that implements [BIP 39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) The github page lists a couple potential options.

We need to be able to convert a phrase to a key/game path, and generate a phrase based on a seed from SeedQuest.

**Comment by westonb7** [comment]
Diceware integration is now working. Some tweaks still need to be made on the front end and back end, but it is functional.

I couldn't find a library compatible with Unity, so I rebuilt a simple BIP 39 library in unity myself.

Also, for anyone who is reading this and gets the bright idea to siphon off the Eth in the address generated by the seed phrase below - there is no account associated with the below seed phrase (in fact it might not even be a valid seed phrase in the first place - it's just used for testing).

<img width="764" alt="Screen Shot 2019-06-18 at 4 37 19 PM" src="https://user-images.githubusercontent.com/30869523/59724617-bca65100-91e7-11e9-9eb8-07821405879c.png">
<img width="764" alt="Screen Shot 2019-06-18 at 4 37 06 PM" src="https://user-images.githubusercontent.com/30869523/59724620-be701480-91e7-11e9-879f-fc4ee94d2c34.png">
