### ISSUE TITLE
CLI get last command entered with 'up' key

### ISSUE THREAD

**Issue by michaelmendoza** [reputage/seedQuest#264]
**Is your feature request related to a problem? Please describe.**
Trying to make the CLI easier to use

**Describe the solution you'd like**
CLI get last command entered with 'up' key. You should store the commands entered into a list and then each press of the up key goes through that list of previous commmands. 'down' key should go throught that list in the opposite order.

**Comment by michaelmendoza** [comment]
i.e. up/down go through the list of previous commands. Try to mimic the same functionality as a mac terminal

**Comment by westonb7** [comment]
Change made in the 'console-commands' branch.

**Comment by michaelmendoza** [comment]
Can you show some screenshots of this functionality?

**Comment by westonb7** [comment]
<img width="462" alt="Screen Shot 2019-03-08 at 6 09 37 PM" src="https://user-images.githubusercontent.com/30869523/54063942-6760a980-41cd-11e9-81a0-d1f46fa5b0f7.png">

**Comment by michaelmendoza** [comment]
@westonb7  Does pressing 'down' also go through the list in the opposite direction as 'up'?
