### ISSUE TITLE
CLI Improvements

### ISSUE THREAD

**Issue by michaelmendoza** [reputage/seedQuest#265]
**Is your feature request related to a problem? Please describe.**
Trying to make CLI more user friendly and to mimic standards of terminal CLI

**Describe the solution you'd like**
- [x] Entering 'help command' should give information on the commmand
- [x] Entering a command should echo the command i.e. you type 'showcolliders' the CLI should echo '> showcolliders' in the textbox instead of empty space. Mimic mac terminal behavior

**Comment by westonb7** [comment]
Changes made in the 'console-commands' branch.

**Comment by michaelmendoza** [comment]
@westonb7  Can you show screenshots of this functionality?

**Comment by westonb7** [comment]
Example of 'help command' displaying more details on a specified command:
<img width="598" alt="Screen Shot 2019-03-08 at 6 11 20 PM" src="https://user-images.githubusercontent.com/30869523/54063965-9a0aa200-41cd-11e9-9fb8-f76b89cbf468.png">
Example of entered commands being echoed:
<img width="459" alt="Screen Shot 2019-03-08 at 6 09 27 PM" src="https://user-images.githubusercontent.com/30869523/54063975-a1ca4680-41cd-11e9-95e4-adaa44b5736e.png">

**Comment by michaelmendoza** [comment]
Awesome!
