### ISSUE TITLE
Islands: Trough display text is not aligned like rest of interactables/Display text does not face camera

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#267]
**Description**
(P1)"Trough" Display text is also set sideways compared to rest of Campground interactables, making it hard to read. 

(P4)The text display can be hard to read in 3D, since player can be behind objects and the text display will appear backwards. 

**To Reproduce**
1. Go to Islands Prototype
2. Go to Campgrounds area
3. Walk near campfire, look towards Trough
4. See "Trough" display text not aligned similarily to rest of 

**Expected Behavior**
Trough text looks aligned like the rest of the objects. 
Display text is set to face camera. 

**Screenshots**
Trough Display Text problem: 
![image](https://user-images.githubusercontent.com/6446247/54148772-1087e980-43f2-11e9-9a5f-d68cf635860d.png)

Text is backwards:
![image](https://user-images.githubusercontent.com/6446247/54148847-357c5c80-43f2-11e9-8eae-d373856d6c5e.png)

**Device Info (please complete the following information):**
 - OS: Win 10 x64
 - Version 2019_03_08_V2

**Comment by cameronthughes** [comment]
text is fixed, I will switch to rotate? Fixed Through.
