### ISSUE TITLE
Islands: Firepit Interactable has no Prev Image

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#269]
**Description**
When player selects over Fire Pit interactable or gets the firepit interactable, it displays no image. 

**To Reproduce**
1. Go to Islands - Learn
2. Hope that you'll get FirePit as a seed interactable 
3. Look at Preview Image
4. See that there's no preview image for FirePit

**Expected Behavior**
When you have selected FIrePIt interactable, you'll see it in the Next Preview bubble. 

**Actual Behavior**
No image in Next Item Preview bubble. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6446247/54150277-4aa6ba80-43f5-11e9-9f96-f6b84dd9b3da.png)

**Device Info (please complete the following information):**
 - OS: Win 10 x64
 - Version 2019_03_08_V2

**Comment by cameronthughes** [comment]
Scaling issue, fixed.
