### ISSUE TITLE
Islands: Banner Interactable is blocked by Tracker in Learn Mode

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#270]
**Description**
In Islands Prototype, when user has "Choose Banner" as an interactable, It's difficult to see the Interactable Text/arrows over white backdrop and there's a UI tracker on top of it. 

**To Reproduce**
1. Go to Islands - Learn
2. Play until you get Choose Banner as an option
3. Find Banner in Castle
4. See that it's difficult to see text UI on white backdrop and that the UI tracker is blocking. 

**Expected Behavior**
UI Tracker is above Text UI and Text could be bigger font

**Screenshots**
![image](https://user-images.githubusercontent.com/6446247/54151581-5fd11880-43f8-11e9-992e-8c5d84ef383c.png)

**Device Info (please complete the following information):**
 - OS: Win 10 x64
 - Version 2019_03_08_V2

**Comment by michaelmendoza** [comment]
Fixed
