### ISSUE TITLE
CLI: Make CLI toggle with ` mark. 

### ISSUE THREAD

**Issue by michaelmendoza** [reputage/seedQuest#272]
**Is your feature request related to a problem? Please describe.**
It is a little annoying to constantly use the ` mark when using the CLI

**Describe the solution you'd like**
It would better to make the ` toggle the CLI i believe. You can use your fade out animation when you toggle off though if you want.

**Comment by westonb7** [comment]
CLI now stays active and does not automatically fade out. ` mark is used to toggle on and off. Changes made in console-commands branch.
