### ISSUE TITLE
CLI: Add a side scrollbar/arrows to go through past command history

### ISSUE THREAD

**Issue by michaelmendoza** [reputage/seedQuest#273]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to see the past command history. Once your command history display fills up you can't see the previous commands. 

**Describe the solution you'd like**
It would be nice to have a scrollbar to go through the past history.

**Comment by westonb7** [comment]
CLI now has vertical scrolling. It doesn't have a visible scrollbar, but I can put one in. Changes made in console-commands branch
