### ISSUE TITLE
Flatlands/Mindpalace: After finishing prototype, Rehearse mode does not put player back to Level Select

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#281]
**Description**
After user clears MindPalace/Flatlands Learn Mode, when they get the option at the Key Recovered popup to Rehearse again, the user does not get sent back to Level Select. 

**To Reproduce**
1. Go to either MindPalace/Flatlands, Learn mode
2. Continue with the game until you get to the Key Recovered scene
3. Select Rehearsal Mode
4. Player restarts in level that they were just in, but interactable tracker and prev bubble still persist. 

**Expected Behavior**
After clearing level and selecting Rehearsal Mode, player returns to Level select to redo the pattern that they just finished. 

**Actual Behavior**
After clearing level and selecting Rehearsal Mode, player restarts in current scene with the interactable tracker still visible and the prev bubble, but not able to rehearse the pattern that they just learned. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6446247/54318989-50db9900-45a5-11e9-9e29-a047e60b9419.png)

**Device Info (please complete the following information):**
 - OS: Win 10 x64
 - Version 2019_03_13_V3

**Comment by michaelmendoza** [comment]
Fixed in V0.0.10
