### ISSUE TITLE
Global: Rehearsal mode - No way to undo selection once added.

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#282]
**Description**
During rehearsal mode, there is no way for player to undo the selection that they've made. 

**To Reproduce**
1. Go to Flatlands/Mindpalace prototype, Rehearsal Mode
2. Select any level
3. Select any interactable and hit checkmark above it.  
4. No way to undo action and is recorded already.

**Expected Behavior**
If player selects interactable, perhaps they can select interactable again and see that there's now an undo button next to checkmark. Like one of these; 
![image](https://user-images.githubusercontent.com/6446247/54319629-75387500-45a7-11e9-8954-7aef96b99af2.png) But perhaps reversed. Once selected, item reverts back to default item and player can click through again and choose the item again. 

**Device Info (please complete the following information):**
 - OS: Win 10 x64
 - Version 2019_03_13_V3

**Comment by michaelmendoza** [comment]
<img width="943" alt="Screen Shot 2019-03-19 at 1 38 36 AM" src="https://user-images.githubusercontent.com/4431065/54588146-cac9b300-49e7-11e9-9b6f-697d46ca9cc8.png">
