### ISSUE TITLE
Flatlands/Mindpalace: Need UI to indicate Level Select is in Rehearsal or Recall mode. 

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#283]
**Description**
For the Flatlands and Mindpalace sequences, it seems confusing if the player is dropped straight into the the Level Select without any prompt. It might help if we have a header that says whether the player is in rehearsal mode or recall mode. 

**Describe the solution you'd like**
Under the Title of the Level in Level Select, it would be nice to have a subheader that indicates Tutorial Mode/Rehearsal Mode/Recall Mode

**Describe alternatives you've considered**

Perhaps a UI text prompt specific to the condition where you get to Level select - 

IE., From prototype level select, you select "Learn", then a prompt pops up at Level Select - "HOW TO PLAY - Welcome to Flatlands! In Learn Mode, we have a random seed generated for you to decrypt, so you can only choose the highlighted levels and items. You will need to go through two levels to decrypt the entire seed. Have fun practicing!" 

IE., From Key Recovery, you select "Rehearse Mode", then user goes back to Level Select and a prompt appears "REHEARSAL MODE - Looking to practice decrypting your seed? Select the highlighted levels and items again."

**Additional context**
![image](https://user-images.githubusercontent.com/6446247/54323326-00206c00-45b6-11e9-9db3-e88563cb075e.png)

**Comment by michaelmendoza** [comment]
<img width="685" alt="Screen Shot 2019-03-18 at 2 44 51 PM" src="https://user-images.githubusercontent.com/4431065/54562322-69282b00-498c-11e9-8b1f-b394f41f2604.png">
