### ISSUE TITLE
Tutorial UI: 'Skip' button doesn't work for all prototypes

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#285]
**Description**
The Skip button doesn't skip the tutorial in all prototypes. It's functional in the SeedQuest and Mind palace prototypes, but not the others.

**Expected Behavior**
Skip button should skip through the rest of the tutorial.

**Actual Behavior**
Skip button does nothing when clicked.

**Device Info (please complete the following information):**
 - OS: Mac
 - Version v4

**Comment by michaelmendoza** [comment]
Fixed
