### ISSUE TITLE
Bug: exiting pause menu causes loss of player control

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#286]
**Description**
Accessing pause menu, and exiting by clicking the 'X' button causes loss of control of the player when game resumes. Tested in all prototypes in rehearsal mode.

**To Reproduce**
Begin rehearsal mode in any prototype, press 'esc' to open pause menu, click on 'X' button to close menu. 

**Device Info (please complete the following information):**
 - OS: Mac
 - Version v4

**Comment by michaelmendoza** [comment]
Fixed with #300
