### ISSUE TITLE
Bug: pause menu exit button doesn't work in memory palace prototype

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#287]
**Description**
The 'X' button used to exit the pause menu is not functional in the memory palace prototype.

**To Reproduce**
Play memory palace in rehearsal mode, press 'esc' to enter pause menu, click on 'X' button.

**Expected Behavior**
Pause menu should close.

**Actual Behavior**
Nothing happens.

**Device Info (please complete the following information):**
 - OS: Mac
 - Version v4, played in windowed mode

**Comment by michaelmendoza** [comment]
Fixed with #300
