### ISSUE TITLE
Bug: hitboxes for pause menu buttons is off

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#288]
**Description**
The 'hitboxes' or colliders for the buttons in the pause menu are not aligned properly with the buttons themselves. Tested while in windowed mode, may be related to screen resolution. Tested in multiple prototypes.

**To Reproduce**
Play any prototype, press 'esc' to enter pause menu, and try hovering over the different buttons.

**Expected Behavior**
Every button should be highlighted while the cursor hovers over the respective buttons.

**Actual Behavior**
The wrong button can be highlighted while hovering over the menu, and the wrong button can be activated if the user clicks while hovering over the wrong space.

**Screenshots**
<img width="719" alt="Screen Shot 2019-03-14" src="https://user-images.githubusercontent.com/30869523/54391420-61097c00-466a-11e9-80cd-d9d878f02947.png">
It's hard to see because the highlighted color of buttons is subtle, but in the above screenshot, the mouse is to the right of the quit button, but the `Quit` button is highlighted. The `Main menu` button can be highlighted while the cursor is over the `Quit` button

**Device Info (please complete the following information):**
 - OS: Mac
 - Version v4, windowed mode

**Comment by michaelmendoza** [comment]
Fixed with #300
