### ISSUE TITLE
Memory lab: aquarium has no collider

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#289]
**Description**
The 'aquarium', just to the right of the starting location in the memory lab, has no collider, and the player can walk through it.

**Screenshots**
<img width="710" alt="Screen Shot 2019-03-14 at 1 33 28 PM" src="https://user-images.githubusercontent.com/30869523/54391663-205e3280-466b-11e9-8df2-63769713757d.png">
<img width="711" alt="Screen Shot 2019-03-14 at 1 33 16 PM" src="https://user-images.githubusercontent.com/30869523/54391669-22c08c80-466b-11e9-87c7-359013c55d3c.png">

**Device Info (please complete the following information):**
 - OS: Mac
 - Version v4

**Comment by michaelmendoza** [comment]
Added
