### ISSUE TITLE
Memory lab: door in wonderland has no collider

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#290]
**Description**
The door and the right wall of the wonderland area in the memory lab has no collider and the player can walk through it.

**Screenshots**
<img width="718" alt="Screen Shot 2019-03-14 at 1 34 49 PM" src="https://user-images.githubusercontent.com/30869523/54391832-b003e100-466b-11e9-83bd-86e9aa6bbcd6.png">
This is the wall in question
<img width="716" alt="Screen Shot 2019-03-14 at 1 34 47 PM" src="https://user-images.githubusercontent.com/30869523/54391798-9bbfe400-466b-11e9-9efd-6e60b89d54a7.png">
Player is halfway through the wall here.
<img width="710" alt="Screen Shot 2019-03-14 at 1 34 45 PM" src="https://user-images.githubusercontent.com/30869523/54391802-9e223e00-466b-11e9-80e4-3e307bf0d3d5.png">
I think this area isn't meant to be accessible yet.

**Device Info (please complete the following information):**
 - OS: Mac
 - Version v4

**Comment by michaelmendoza** [comment]
Added Box Colliders to walls that needed them
