### ISSUE TITLE
Flatlands: pushing 'h' to access level select doesn't always work

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#292]
**Description**
At the end of a level in flatlands, the user is prompted to push 'h' to access the level select, but sometimes pushing 'h' here doesn't do anything. Opening the CLI and pushing 'h' allowed me to access the level select again.

**To Reproduce**
I'm not 100% sure how to reproduce this problem, it only happens about 1/3rd of the time, unfortunately.

**Expected Behavior**
Pushing the 'h' key should immediately bring up the level select screen.

**Actual Behavior**
Multiple presses of the 'h' key did nothing.

**Device Info (please complete the following information):**
 - OS: Mac
 - Version v4, windowed mode

**Comment by ntelfer** [comment]
This is on purpose.  If you switch after starting a seed it breaks things.  

If a user types 'h' and the can't switch we should add a pop up that lets them know what's going on.

**Comment by westonb7** [comment]
To clarify, this was _after_ performing all the actions in the level, and _being prompted_ to press 'h' to access the level select, not while still in the middle of the level.

**Comment by michaelmendoza** [comment]
Should be fixed. How LevelClear screen using a button to go to LevelSelect Menu. In V0.1.0
