### ISSUE TITLE
Flatlands: can't click interactable checkboxes in the upper left hand corner of the screen.

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#293]
**Description**
Checkboxes for interactables can't be clicked if the checkbox is in the upper left hand corner of the screen. Possibly because the text displaying the prototype name is in the way, blocking the collider. If the player moves so that the checkbox is out of the corner, clicking works again.

**Screenshots**
<img width="707" alt="Screen Shot 2019-03-14 at 3 25 52 PM" src="https://user-images.githubusercontent.com/30869523/54392834-30c3dc80-466e-11e9-9507-2c649d30a202.png">
The piano's checkbox can't be clicked here

<img width="713" alt="Screen Shot 2019-03-14 at 3 28 22 PM" src="https://user-images.githubusercontent.com/30869523/54392846-3ae5db00-466e-11e9-9760-b04143cfdb07.png">
The tree's checkbox can't be clicked here, either.

**Device Info (please complete the following information):**
 - OS: Mac
 - Version v4

**Comment by michaelmendoza** [comment]
Fixed with #300
