### ISSUE TITLE
Flatlands: sometimes can't click the checkbox of host interactable in Nonna's restaurant

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#294]
**Description**
Sometimes the user can't click the checkbox of host interactable in Nonna's restaurant. Does not happen all the time, so it's difficult to reproduce reliably. May be related to Issue #293 

**Screenshots**
<img width="716" alt="Screen Shot 2019-03-14 at 3 28 41 PM" src="https://user-images.githubusercontent.com/30869523/54393070-dc6d2c80-466e-11e9-858c-74b98a46c4e7.png">
Here the user is unable to click on the host's checkbox. Here it should be far enough away from the corner to not be the same issue as #293 but it's hard to say.

**Device Info (please complete the following information):**
 - OS: Mac
 - Version v4

**Comment by michaelmendoza** [comment]
Removed Checkbox from nextprevselect InteractableUI. So no longer an issue
