### ISSUE TITLE
Seedquest: Floating weapon rack in the sky

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#296]
**Description**
There's a floating weapon rack in the sky of the seedquest prototype. It's different from the weapon rack interactable in the castle, and doesn't appear to be an interactable.

**Screenshots**
<img width="718" alt="Screen Shot 2019-03-14 at 1 32 07 PM" src="https://user-images.githubusercontent.com/30869523/54393601-31f60900-4670-11e9-8d7e-cb1ae7b5b396.png">
Here it is, floating in the sky.

**Device Info (please complete the following information):**
 - OS: Mac
 - Version v4

**Comment by michaelmendoza** [comment]
Moved InteractablePreviewUI PreviewRig to y = -2000. Now appears underneath the island and non-visable
