### ISSUE TITLE
Memory palace: level begins with an arrow and a waypoint on the cursor

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#297]
**Description**
Sometimes the level begins with an arrow and a waypoint over the cursor. This also unfortunately prevents the user from being able to click on anything.

**To Reproduce**
Unfortunately, I can't reproduce this reliably, and it's only happened to me once.

**Screenshots**
<img width="706" alt="Screen Shot 2019-03-14 at 1 40 04 PM" src="https://user-images.githubusercontent.com/30869523/54393856-e09a4980-4670-11e9-97fb-525cd9cc0231.png">

**Device Info (please complete the following information):**
 - OS: Mac
 - Version v4

**Comment by michaelmendoza** [comment]
Same as #302

**Comment by michaelmendoza** [comment]
Fixed
