### ISSUE TITLE
Screenshot Feature

### ISSUE THREAD

**Issue by michaelmendoza** [reputage/seedQuest#299]
Could be cool to have the ability to take screenshot native in the app

**Comment by westonb7** [comment]
I made a screenshot script that can do this in a new branch ('Screenshot'). Adding the 'ScreenShot' monobehavior anywhere in a scene should find the main camera object and will save a screenshot when the backslash key `\` is pressed. The screenshot file will get saved to the 'Experiments/SeedQuestSandbox/Assets/screenshots/' folder by default if used. I haven't added to any scenes though.
