### ISSUE TITLE
Survey server: server cannot accept post requests if the body is longer than 1000 characters

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#305]
**Description**
Post requests to the survey server fail if the body is longer than 1000 characters long. I can cut down the length of the questions being sent to the server, but since there are open-ended questions in the survey, it's impossible to know for sure how long the intended post request body will be.

**Actual Behavior**
Server doesn't respond, error message received is "Empty reply from server"

**Additional context**
Tested both in unity (using UnityWebRequest), and also using curl, so it's not a unity-specific problem.

**Comment by ntelfer** [comment]
This appears to be an issue with the header value "Expect: 100-continue".  This is a way to increase server bandwidth by allowing the server to deny requests with large bodies.  In our case we don't really need this and it should be disabled.  With curl you can disable it like so:

`curl -H "Content-Type: application/json" -H "Expect:" -X POST -d 'some data' `

I'm assuming that if all else fails you could probably tell the unity framework to set the header value to "Expect:" and give it an empty string.

**Comment by westonb7** [comment]
Issue has been resolved by changing the http settings in unity. Changes are in the 'survey-debugging' branch. Limits on user response length have been removed as well.
