### ISSUE TITLE
It's possible to submit empty survey data

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#311]
**Description**
There is no validation that a user answered the survey questions before the survey data is submitted.

**To Reproduce**

1. Download V5 of the prototype
2. Click the Survey button
3. Click the next arrows till you get to the submit screen
4. Submit the survey

**Expected Behavior**
A prompt appears that says they can't submit an empty survey response.  (Not sure if we should require all questions to be answered or not? @SmithSamuelM @michaelmendoza  but we should at least check that one of the questions has an answer.)

**Actual Behavior**
An empty survey is submitted and the game quits

**Device Info (please complete the following information):**
 - OS: Windows 10
 - Version V5

**Comment by ntelfer** [comment]
For this it's better that we get partial data than none at all.  Only require that one question has a response.

- [ ] Add prompt

- [ ] If the survey has no response the prompt won't allow a submit

- [ ] If the survey has empty questions ask if they are sure they want to leave them blank.  A no response sends them back to the survey, a yes submits the survey.

**Comment by michaelmendoza** [comment]
Updated in Survey. Should be in V0.1.0
