### ISSUE TITLE
Cant Quit From Prototype Select Screen in V5 Build

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#312]
**Description**
Pressing Esc from the prototype select screen does nothing. If you are in a specific prototype it works fine.

**To Reproduce**
1. Open the V5 build
2. Press Esc key

**Expected Behavior**
The Quit menu appears

**Actual Behavior**
Nothing happens

**Device Info (please complete the following information):**
 - OS: Windows
 - Version: V5

**Comment by michaelmendoza** [comment]
Fixed in V0.0.6
