### ISSUE TITLE
Interactables will sometimes not count when you click their checkbox in rehearsal mode.

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#325]
**Description**
Sometimes while playing in rehearsal mode, after clicking a checkbox to confirm an interactable action, the checkbox will vanish, but the preview will still prompt you to do the same action you just 'confirmed', and the seed progress bar won't change, indicating that the action wasn't logged in the interactable log.

**To Reproduce**
This one is hard to reproduce, but it seems to happen most frequently with the 'choose king' interactable in the islands(seedquest) prototype, and the 'stump' interactable in the memory palace prototype. It seems to happen more when there's another interactable behind the checkbox of the interactable I'm trying to act on.

**Screenshots**
<img width="716" alt="Screen Shot 2019-03-22 at 7 51 05 AM" src="https://user-images.githubusercontent.com/30869523/54828491-e9df7380-4c79-11e9-9fe4-1a8b5e0ba6cb.png">
Here I'm about to click the checkbox for this interactable.

<img width="715" alt="Screen Shot 2019-03-22 at 7 52 46 AM" src="https://user-images.githubusercontent.com/30869523/54828495-eba93700-4c79-11e9-9cab-cd5147437da1.png">
Here I have just clicked the checkbox, and the checkbox has disappeared, but I'm still prompted to choose the egg king, and the seed progress bar has not changed.

<img width="719" alt="Screen Shot 2019-03-22 at 8 00 17 AM" src="https://user-images.githubusercontent.com/30869523/54828505-efd55480-4c79-11e9-8877-13de0a79ca8b.png">
Same thing here but with the stump interactable.

<img width="718" alt="Screen Shot 2019-03-22 at 8 00 25 AM" src="https://user-images.githubusercontent.com/30869523/54828509-f368db80-4c79-11e9-80ff-216ea63ec9da.png">
Again, checkbox is gone, seed progress is the same.

**Device Info (please complete the following information):**
 - OS: Sierra
 - Version v0.0.6
 - Device: Mac

**Comment by michaelmendoza** [comment]
Removed Checkbox from nextprevselect InteractableUI. So no longer an issue
