### ISSUE TITLE
Main menu: 'Controls' for some prototypes is slightly off

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#326]
**Description**
The 'controls' for both the Cliffsides and Memory palace prototypes are slightly wrong. Cliffsides controls say you can move with WASD, and memory palace says you can move by clicking on the ground.

**Screenshots**
<img width="719" alt="Screen Shot 2019-03-22 at 8 02 22 AM" src="https://user-images.githubusercontent.com/30869523/54828831-a3d6df80-4c7a-11e9-800a-ac8503ce149e.png">
<img width="715" alt="Screen Shot 2019-03-22 at 8 02 26 AM" src="https://user-images.githubusercontent.com/30869523/54828834-a5a0a300-4c7a-11e9-8523-da4492f07ca3.png">

**Device Info (please complete the following information):**
 - OS: Sierra
 - Version v.0.0.6
 - Device: Mac

**Comment by michaelmendoza** [comment]
Fixed in v0.1.0
