### ISSUE TITLE
Improvements to Action selection for interactables

### ISSUE THREAD

**Issue by michaelmendoza** [reputage/seedQuest#330]
**Is your feature request related to a problem? Please describe.**
The probelm is consisently confirming a selection of an interactable action

**Describe the solution you'd like**
I would like to change the current system for the interactables with the left and right arrows. New behavior: 
1) Click on interactable or arrow to get to desired action
2) Click (for a sec) and hold interactable or label to confirm
3) Make label a bar and have the bar animate fill as you hold to confirm
4) After confirm, make a checkmark appear above and have it slowly move up and fade away 1 sec later
5) After confirmation have text appear below the partial decrypted key say : 'You have completed X of 8 actions' and have it fade away 1 sec later
6) At same time make bar animate fill and have the border flash and pulse the size of bar a little

**Comment by ntelfer** [comment]
I really like this idea.  I think it would help the UX a lot.

**Comment by michaelmendoza** [comment]
Thanks! Ya, I think it'll be a big improvement. I'm been thinking a lot how to improve it and been talking to Jane about it.
