### ISSUE TITLE
Tutorial: can't click the 'next' button on one of the slides

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#340]
**Description**
Unable to click the 'next' button for some of the tutorial slides. Skip button can still be pressed though. Possibly because the 'key progress' object is in front of the 'next' button.
Problem found in both the seedquest and memory lab prototypes.

**Screenshots**
<img width="720" alt="Screen Shot 2019-03-27 at 10 52 24 AM" src="https://user-images.githubusercontent.com/30869523/55096595-d66c4800-507f-11e9-8794-3c6dc8c0cfd2.png">
<img width="718" alt="Screen Shot 2019-03-27 at 10 54 07 AM" src="https://user-images.githubusercontent.com/30869523/55096605-d8cea200-507f-11e9-842e-55d67193d9aa.png">

**Device Info (please complete the following information):**
 - OS: Sierra
 - Version v0.0.9
 - Device: Mac

**Additional context**
Played in 'windowed' mode, resolution 1440x900. Demo looks great!

**Comment by ntelfer** [comment]
I think this may be related to screen size.  On my windows machine I don't see this issue.

**Comment by westonb7** [comment]
Yes, it's likely that this doesn't happen most of the time. It's probably the case on my machine because of the resolution I used and because I was in 'windowed' mode.

**Comment by michaelmendoza** [comment]
Fixed in V0.0.11. Reordered the HUD elements sorting order. Tutorial has higher priority than InteractableProgressUI now.
