### ISSUE TITLE
Interactables default mode

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#342]
While playing the game it's common for one of your actions to be to select an interactable's default mode, but when you walk up to it it wont let you select without first shuffling through the options.  I think this is a remnant of the old selection mode with the checkboxes.

For example in the islands prototype the fire pit has a chicken cooking on it.  A players path tells them to select the chicken cooking, they approach the fire pit see the chicken and attempt to select it but nothing happens. when they release the click the interactable changes to the same thing and then they have to click and hold again.

I propose we change this so you can select any interactable without having to first click it.

**Comment by michaelmendoza** [comment]
Interesting Idea. The only problem is the default mode isn't an action option for an intractable. The interactable has a default state, and then actions that change state. What a creator of an interactable can do is artificially create an action where the action is to do nothing. This is probably what you are referring to. 

I'm not sure what is the best way to change this. We could have a default state as part of interactables that have an action. And then only add 3 actions for an interactable. But what is the creator of the interactable doesn't want to have a default state action? 

Something we can continue to talk and think about.
