### ISSUE TITLE
Islands has a floating sheet

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#343]
**Description**
Next to the tent there is a floating sheet.  It's only viewable from certain angles.

**To Reproduce**
1. Go to islands prototype
2. stand between the trees and the people around the fire pit
3. look at the tent

**Expected Behavior**
There is nothing floating in the sky

**Actual Behavior**
There is a white sheet floating above the tent

**Screenshots**
![image](https://user-images.githubusercontent.com/8583797/55098084-c9048d00-5082-11e9-8be7-4870e1abf2f3.png)

**Device Info (please complete the following information):**
 - OS: windows
 - Version 0.0.9

**Additional context**
I noticed this when I was prompted to select the orange tent cover.

**Comment by ntelfer** [comment]
On further inspection the white sheet only appears when you have your cursor hovering on the tent.

**Comment by michaelmendoza** [comment]
Fixed in V0.0.10
