### ISSUE TITLE
New Select Mode Changes Interactable After Selection Completes

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#344]
**Description**
When you hold down to select an action the game is registering this as a click so after selecting your action when you release it moves to the next action in the rotation instead of staying on the one you selected.

**To Reproduce**
1. Go to Islands
2. Click and hold to select an action
3. Release the click when the bar fills up

**Expected Behavior**
The action is selected and the interactable stays on the action you selected

**Actual Behavior**
The action is selected, but the interactable moves to the next option

**Device Info (please complete the following information):**
 - OS: Windows
 - Version 0.0.9

**Comment by michaelmendoza** [comment]
Updated to stay with same interactable after click and hold. Moves to next interactable if click and hold is less than 0.25 secs.
