### ISSUE TITLE
Investigate OTP

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#35]
- Investigate algorithms that could be used to generate OTP from seed

**Comment by westonb7** [comment]
Many OTP key generation algorithms use a random seed to generate the key one character at a time. Something similar to this:

`pad = [0]*keylength
random.seed(seed)
for i in range(keylength):
 pad[i] = str(random.getrandbits(16))`

There's also other algorithms that generate the OTP key using '/dev/random' .

Also, it seems the libnacl.utils library can be used to generate a secure random seed as a nonce.

`import libnacl.utils
nonce = libnacl.utils.rand_nonce()
random.seed(nonce)`

**Comment by SmithSamuelM** [comment]
The Seed should be generated with rand_nonce and the OTP with the blake2 function. See the white paper it spells it out.

**Comment by westonb7** [comment]
Which white paper? This one?
https://github.com/SmithSamuelM/Papers/blob/master/whitepapers/DecentralizedAutonomicData.md

**Comment by SmithSamuelM** [comment]
Yes
