### ISSUE TITLE
Welcome screen text goes off the side of the screen

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#355]
**Description**
The 'Welcome' screen text goes off the side of the screen. Tested in both windowed mode and in full screen mode.

**Screenshots**
<img width="1440" alt="Screen Shot 2019-04-02 at 9 41 58 AM" src="https://user-images.githubusercontent.com/30869523/55416395-f3939180-552b-11e9-925e-ff2e070cd877.png">
Full screen mode above.
<img width="1002" alt="Screen Shot 2019-04-02 at 9 42 53 AM" src="https://user-images.githubusercontent.com/30869523/55416423-fb533600-552b-11e9-96a6-313d1407bee9.png">
Windowed mode above.

**Device Info (please complete the following information):**
 - OS: Sierra
 - Version v0.0.14
 - Device: Mac

**Comment by michaelmendoza** [comment]
Fix for v0.1.0
