### ISSUE TITLE
Prototype select: 'Controls' button no longer displays the controls for the prototype when pushed.

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#356]
**Description**
In the prototype select menu, pushing the 'controls' button in the top right of the screen no longer displays the controls for the selected prototype. Tested for all prototypes in the menu, tested in both windowed and full screen mode.

**To Reproduce**
1. Go to the prototype select menu
2. Click on any prototype
3. Click on the 'controls' button in the top right corner

**Screenshots**
<img width="713" alt="Screen Shot 2019-04-02 at 9 47 11 AM" src="https://user-images.githubusercontent.com/30869523/55416859-d14e4380-552c-11e9-8e0a-9fee73b3319e.png">
It's hard to show with just a screenshot, but here is the main menu after clicking the controls button.

**Device Info (please complete the following information):**
 - OS: Sierra
 - Version v0.0.14
 - Device: mac

**Comment by michaelmendoza** [comment]
Fixed for v0.1.0
