### ISSUE TITLE
Update SeedQuest Explanation to be Less Technical

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#364]
We tend to explain what SeedQuest is and does in semi technical terms.  Based on survey feedback people weren't understanding SeedQuest's purpose.  They thought that SeedQuest was meant to help a user memorize the individual characters of their seed.  Here is a possible way to explain SeedQuest in more layman's terms:

SeedQuest translates your seed or private key into game actions so there is no need to memorize random characters.  Instead you simply memorize game actions and SeedQuest will translates them back into your original seed or private key.

**Comment by jasukim** [comment]
New Tutorial by Andy and Brady fixes this.
