### ISSUE TITLE
Castle Beach Lighting Is Messed Up

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#376]
**Description**
The lighting in the Castle Beach scene seems to be broken.  It used to be a sunset but I'm not sure what it is now.

<img width="1196" alt="Screen Shot 2019-04-27 at 5 06 31 PM" src="https://user-images.githubusercontent.com/8583797/56855994-d70e2d80-690e-11e9-8129-9558376371aa.png">

**Comment by westonb7** [comment]
Castle beach lighting now seems to be working as intended.
