### ISSUE TITLE
Dino Safari Ice Age Exhibit Interactables Are Opaque Instead Of See Through

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#379]
**Description**
The individual interactables have an object inside of them that make each one unique, but the glass is opaque so you can't see them.

**Screenshots**
<img width="290" alt="Screen Shot 2019-04-28 at 3 46 05 PM" src="https://user-images.githubusercontent.com/8583797/56870450-c1f7d400-69cc-11e9-9293-53a8fe1c8478.png">

**Comment by jasukim** [comment]
Should be fixed now
![image](https://user-images.githubusercontent.com/6446247/57047491-ddf6b200-6c26-11e9-8caf-f4da66a210c0.png)
