### ISSUE TITLE
Seeds In SeedQuest

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#380]
**Edit**
This was brought up by playing SeedQuest in recall mode to generate a demo seed to show off.  When we generated the seed using recall mode, copied and pasted it into rehearse mode the actions did not always match up with the ones we used in recall mode.

The seeds should be encoded and displayed in HEX throughout the whole game which would make the seed case insensitive.  Each piece of the game has been worked on by different people and we think that it's in hex throughout but no one has actually checked.  This could be a potential cause of the bug above.

**Comment by westonb7** [comment]
Input seeds can be either capitalized or lowercase and it shouldn't matter - the backend processes the input string in a way that is case-insensitive.

Output strings are always capitalized by default as a result of using the built-in `BitConverter` library.

**Comment by ntelfer** [comment]
OK thanks for checking. This may need to be updated in the future to whatever format is industry standard so that when users need to transfer the seed to another platform they don't run into issues.

**Comment by westonb7** [comment]
I can also change it to use different data formats for the input/output. We decided on using hex a while ago and never really brought it up again. If we want to use something else like base58/base64/BIP39 I can change it to use another format as well. It's also easy to change the output to default to lowercase letters if we decide we want to do that too.

**Comment by ntelfer** [comment]
Possible causes may be:
1. The seed not being in HEX in all areas of the game.  

2. It could be related to an earlier bug in the 5 prototype version where the user was prompted to select an action that was not part of their seed.  

3. It may be related to the fact that the interactables are not being ordered alphabetically.

**Comment by westonb7** [comment]
The most likely source is the bug in Issue #359 - but it will take more testing to know for sure. Option # 3 is also a reasonable possibility. # 1 seems less likely - I checked throughout the backend code to make sure the seed stays in hex format, and I'm confident that isn't the issue, but it's possible there's something on the front end that isn't handling the input/output seed correctly.

**Comment by westonb7** [comment]
I did some testing and some digging around - since I don't know exactly what seeds you were using when you encountered problems with the current build, I did some testing with new seeds, and from what I can tell the problem you're describing is most certainly the same bug described in issue #359 .
It's also very possible that since this new build has changed a lot of things from the previous build, that there are new bugs that affect seed recovery as well, but it will be hard to tell until we have fixed issue #359 .

**Comment by westonb7** [comment]
Issue #359 has been fixed. It seems that the remaining problems with seeds when completing a recall run, then immediately doing a learn run afterwards mostly have to do with bugs in the menu scripts, and certain things not being properly reset after a completed run through one of the two modes. From what I can find in my tests, the remaining problems have very little to do with the seeds themselves.
