### ISSUE TITLE
REQ: Scene Select - On Hover Shows Scene Preview//Show next scene one at a time

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#381]
**Is your feature request related to a problem? Please describe.**
1.) Currently in Scene Select Window in either Learn/Recover Modes, the user has to click on a scene button first if they want to know what the name/location of the scene is. **There should be a quick way to view what the scene is without having to click on anything, so a user doesn't feel like they're making choices before they're ready.** ((I think this is pretty useful for next build))

2.) Not so much a problem, but currently in Learn Mode the game labels the icons are all visible and the generated Scene Icon Pattern (1-4 indicators) already show up at start. **It would benefit memory/learning purposes if we could introduce the generated Scene Icon Pattern one scene at a time during Learn Mode.** ((Would be nice to have for next build))

**Describe the solution you'd like**
1.) In Scene Select Window, User can hover their mouse over the scene icon button, and on the right side a preview of the level image/label shows up. (Shown in example images below)

2.) During Learn Mode in Scene Select Window, have all icons shaded and unselectable except for the first Scene in the Scene Pattern. Then once user selects the first Scene, display the next Scene Button in the Scene Pattern line up. (Shown in example images below)

**Additional context**
![sceneselect_shadowicon1](https://user-images.githubusercontent.com/6446247/57039422-6c603900-6c11-11e9-8930-70b09f9aec3b.png)
![sceneselect_shadowicon2](https://user-images.githubusercontent.com/6446247/57039423-6c603900-6c11-11e9-8177-2179a93e4a35.png)
![sceneselect_shadowicon3](https://user-images.githubusercontent.com/6446247/57039425-6c603900-6c11-11e9-951f-99f6c37d3365.png)

**Comment by michaelmendoza** [comment]
We now show a preview of the scenes on hover
