### ISSUE TITLE
Cliffsides - can't progress to next action item after accepting certain objects

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#382]
**Description**
When playing through Learn Mode, would try to play through Cliffsides but after accepting certain Objects, user cannot progress because the Preview Window and tracker does not update. 

Using Seed D9CF9CC1DAA28086D5E1184CD538
Specifically, Tent - Red and Tree - Hug does not work. Gravestone interactable does (from a previous attempt)

**To Reproduce**
1. Select Learn Mode, use Seed D9CF9CC1DAA28086D5E1184CD538
2. Play through first scene (Nonna Restaurant) 
3. Start Cliffside Iso, accept the Tent Action
4. Preview Image remains on Tent Action and does not update

**Expected Behavior**
After accepting the Tent Action, game progresses onto next item.

**Device Info (please complete the following information):**
 - OS: Windows
 - Version 5/1/2019 build

**Comment by westonb7** [comment]
I'm unable to recreate this issue with the current build. With the number of changes and bugfixes that we've made recently, it's possible this bug has been fixed along the way while we've been fixing everything else. I'm closing this issue for now, but if you're still seeing it in the future, just re-open it and we'll work on it some more.
