### ISSUE TITLE
Audio Interactables need to have audio cut off when switching between songs. 

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#383]
**Description**
When switching between Audio for Audio Interactables such as the Phonograph/Piano, the sounds do not end when switching between Audio Actions. They instead compound and the user cannot hear the specific song that is displayed for the Audio Interactables. 

**To Reproduce**
1. Play through either Learn/Recover mode for any scene with Audio interactable (Saloon - PIano, Cafe/Campgrounds - Record Player, etc)
2. Play through/Click on the Audio Interactable 
3. Click again to cycle Audio
4. Bask and listen to the weird music you've just created (audio all playing at the same time, ending at different times)

**Expected Behavior**
When user clicks on audio interactable, let song play until user clicks again to cycle with a very very small pause/fade out in between songs (1/4 of a second?).

**Comment by westonb7** [comment]
Fixed in Seed_bugfixing branch.
