### ISSUE TITLE
Need to bring back ESC (Go back to menu option)/Bring back Undo

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#385]
**P1 Bug -** 

1. We need to bring back the ESC key function or perhaps click on GUI button on screen to go back to the Seedquest Menu, like what we had before. 

2.  Will need an undo button and a tutorial explaining its use. Either the U button or unscreen GUI.

**Comment by ntelfer** [comment]
So this is working in some of the old scenes, but it needs to be added to all the scenes.

**Comment by westonb7** [comment]
Updated pause menu is now working in current builds.
