### ISSUE TITLE
Learn Mode Tutorial: User can move around while the Tutorial is still up

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#387]
**Description**

While the tutorial is happening, user can still move around. We may have to overhaul how we do the tutorial anyway though.

**To Reproduce**
1. Start in Learn mode in any scene
2. Choose to go through with tutorial
3. Click around in background while tutorial card is still up
4. See the little dude walking around in the background

**Expected Behavior**
Player does not move until Tutorial is skipped or finished.

**Comment by westonb7** [comment]
This should now be fixed in recent builds.
