### ISSUE TITLE
Link in release.md file is broken

### ISSUE THREAD

**Issue by trentlarson** [reputage/seedQuest#391]
**Description**
Go to https://github.com/reputage/seedQuest/blob/master/docs/releases.md and click on the Mac or PC link and see it broken. 

**To Reproduce**
1. Go to https://github.com/reputage/seedQuest/blob/master/docs/releases.md
2. Click on the Mac or PC link and see it broken. 

**Expected Behavior**

**Actual Behavior**
Broken

**Screenshots**

**Device Info (please complete the following information):**
Mac

**Additional context**

**Comment by ntelfer** [comment]
Fixed.  It now links directly to GitHub's releases page instead of a specific release.
