### ISSUE TITLE
Prevent invalid intractable action 

### ISSUE THREAD

**Issue by michaelmendoza** [reputage/seedQuest#394]
**Description**
In Learn mode, can select invalid action for an interactable

**To Reproduce**
1. In Learn mode
2. Select Action on Interactable

**Expected Behavior**
To prevent action on invalid action

**Actual Behavior**
Prevent action for invalid action of an interactable

**Comment by westonb7** [comment]
This issue has now been fixed - a backend fix has been made in the bugfixing branch, and a frontend fix is in dev.
