### ISSUE TITLE
Interactables Stuck After Selection

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#402]
**Description**
Sometimes while running in learn mode after selecting an item the interactable preview will not continue on to the next object.  You can keep selecting the same object over and over and nothing happens.

This bug is hard to replicate because sometimes it gets stuck and sometimes it doesn't.  I've experienced this bug across multiple scenes.  The latest was the sports scene with the drink, but on subsequent play throughs it did not get stuck on the drink interactable.

**To Reproduce**
Seed Used: 772283D9D40BAC27C6D6D60537D7B35205
It got stuck on the sports scene selecting Drink: Water

**Expected Behavior**
After selecting Drink Water the preview should move on to the next interactable.

**Actual Behavior**
The item shows it was selected, but nothing happens.  You can select the Drink Water option as many times as you want, but you will be stuck there.

**Device Info (please complete the following information):**
 - OS: Mac
 - Version: This is a bug that happens across all current versions as of 5/17/19
 - Device: Mac

**Comment by jasukim** [comment]
I've also written up a similar bug to this last milestone, https://github.com/reputage/seedQuest/issues/382

Also can confirm this happens with the Bar Interactable in Sports where it won't progress to the next scene. 

Used this seed:
D4EA03E22E6D82E5564595B18CE6641C03

**Comment by westonb7** [comment]
I'm unable to recreate this issue with the current build. With the number of changes and bugfixes that we've made recently, it's possible this bug has been fixed along the way while we've been fixing everything else. I'm closing this issue for now, but if you're still seeing it in the future, just re-open it and we'll work on it some more.
