### ISSUE TITLE
Pause menu -  Exit to Menu Screen is broken

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#405]
**Description**
If you play through a scene and bring up the Pause Menu, select the "Exit to Menu Screen" will bring player to an empty Unity Scene instead of the Menu Screen. 

**Device Info (please complete the following information):**
 - OS: Win10
-Version: 0.2.4

**Additional context**

**Comment by westonb7** [comment]
This should be fixed now in the Seed_bugfixing branch. Will need to be merged into dev.
