### ISSUE TITLE
Create Mute BG Audio Button

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#406]
**Is your feature request related to a problem? Please describe.**
The music can drive anyone nuts after a time. Should have a Mute button either on screen or within pause menu.

**Comment by michaelmendoza** [comment]
Added volume control to pause menu 
<img width="938" alt="Screen Shot 2019-05-23 at 6 31 00 AM" src="https://user-images.githubusercontent.com/4431065/58252867-5cc1a500-7d24-11e9-8c01-d2bdf04a5c2b.png">

**Comment by jasukim** [comment]
Now we just need this feature back again for the New Pause Menu. @westonb7 would you be our man to add this back in?

**Comment by westonb7** [comment]
You bet!
