### ISSUE TITLE
Learn mode does not notify you when you select the wrong action

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#407]
**Description**
Learn mode should either not allow selection of the wrong action/interactable or notify the user if they selected the wrong interactable.  In either scenario invalid interactables should not be added to the reconstructed seed. 

Currently you can select any interactable/action you want and it will count as one of the 18 actions you have to take.  It's possible to take all 18 actions in a single scene since the game doesn't progress to the next scene until you have done the correct 3 actions in order.

**Comment by westonb7** [comment]
Learn mode no longer adds incorrect actions to the interactableLog (changed in the bugfixing branch) but we still need a visual effect to inform them their choice was the incorrect one.

**Comment by westonb7** [comment]
Brady made a UI update for this issue - now a red 'X' appears if the incorrect action is taken in learn mode.
