### ISSUE TITLE
Interactables can enter invalid states that break the game

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#408]
**Description**
If you interact with an interactable and in the process accidentally hover over another interactable it will reset the original interactable. You can still select the reset interactable by clicking and holding it which breaks the game.

**To Reproduce**
1. Go to any scene
2. Go to the first interactable in the list
3. Start clicking through the actions
4. When you get to the action you should take hover over a different interactable
5. Click and hold the interactable you are supposed to interact with

**Expected Behavior**
The action is selected and the preview moves to the next interactable or you can't select the interactable till you click on it again.

**Actual Behavior**
The interactable/action gets selected the preview area breaks(Won't advance to the next action) and even if you select the correct actions the game does not progress to the next scene.

**Device Info (please complete the following information):**
 - OS: Mac
 - Version 0.2.5

**Comment by westonb7** [comment]
I've added a fix in the bugfixing branch - selecting an action, then hovering over a different interactable, then clicking on the first interactable should now cause the preview to update properly, and should allow the player to progress to the next scene as normal.
