### ISSUE TITLE
Action Line Up: Scene Interactables show the wrong sub-action

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#410]
**Description**
During Learn Mode, when the user comes across the Action Line Up for a scene that contains double of the same Interactable, it will show the wrong Sub-header Item. 

**To Reproduce**
1. Click on Setup Seed
2. Use Seed "EBF8F00E04997A8FA08ED9BBE152281F4"
3. Play through until you see action line up for Space Colony
4. See that there's two Food Machines > Make Candy
5. Play through Space Colony 
6. Error: First Item Hub is Food Machine, but the Sub Action is Make Pizza, Not Candy. 
7. Second Item Hub is Food Machine>Make Candy which is correct. 

**Expected Behavior**
The Action Line Up should have the correct Sub-Action underneath it. Ideally, also the same preview image. 

**Screenshots**
Starting Screen: 
![image](https://user-images.githubusercontent.com/6446247/58279682-e472d800-7d53-11e9-98cf-8ad023e786e9.png)

In Actuality: 
![image](https://user-images.githubusercontent.com/6446247/58279725-02403d00-7d54-11e9-813a-ac768fac2d0b.png)

**Device Info (please complete the following information):**
 - OS: Win 10 x64
 - Version 2019_05_23 v0.2.5

**Comment by westonb7** [comment]
This should now be fixed in the Seed_bugfixing branch
<img width="643" alt="Screen Shot 2019-05-23 at 3 04 38 PM" src="https://user-images.githubusercontent.com/30869523/58286517-2ad43100-7d6c-11e9-8ede-480c2ff30ca1.png">
