### ISSUE TITLE
Learn Mode: Game breaks momentarily after choosing to Replay Scene

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#411]
**Description**
In Learn Mode, after choosing all the Actions and getting to the Level Clear Screen, if the player chooses to "Replay Scene" the game still runs, but the user cannot click on anything or press ESC. However, eventually after clicking/hovering over interactable spots the user can move againa nd press buttons. I'm not sure why this works, or what causes it to get fixed. 

**To Reproduce**
1. Click to Setup Seed
2. Play through any scene generated by the seed
3. When getting to Level Clear Card, hit "Replay Scene"
4. See that the game still runs but the User cannot move or click or press ESC
5. You can move the mouse around and click things and sometimes the game "fixes" itself? 

**Expected Behavior**
Replay game will allow the game to restart over and have the user be able to move around as soon as they can. 

**Device Info (please complete the following information):**
 - OS: Win 10 x64
 - Version 2019_05_23 v0.2.5

**Comment by westonb7** [comment]
This has been fixed in the Seed_bugfixing branch
