### ISSUE TITLE
Undo button lets you undo actions from previous scenes

### ISSUE THREAD

**Issue by ntelfer** [reputage/seedQuest#416]
**Description**
The undo button lets you undo as many actions as you want.

**To Reproduce**
1. Play through one scene
2. Complete a couple actions in scene 2
3. Click the Undo button 3+ times

**Expected Behavior**
You can only undo actions from the current scene, and then the undo button is disabled or doesn't show up

**Actual Behavior**
You can undo all actions till the counter says you've completed 0 of 18.  Once you hit 0 you can still click the undo button and the confirm window appears but nothing happens.

**Device Info (please complete the following information):**
 - OS: Mac
 - Version 0.2.5.2

**Comment by westonb7** [comment]
I've added temporary fix for this in the bugfixing branch - the undo button should no longer allow the user to undo an action from a previous scene, however it still needs a visual UI update to inform the user that they can't undo actions from previous scenes. Right now it just prints a message to the debug log (see UndoUI.cs line 45 in the bugfixing branch).
