### ISSUE TITLE
Debug: Ability to select any scene any number of times for learning mode

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#417]
**Is your feature request related to a problem? Please describe.**
When debugging and recreating bugs for scenes in Learn Mode/Setup Seed mode, the only way to currently check for a specific bug on a specific scene is to refresh the Seed Setup to get a seed that has the scenes you need to check a specific bug for, OR play through recovery mode and check certain gameplay issues such as movement, graphics, or UI preview bubble issues (but not UI tracker)** issues through there. 

**To toggle this, you need to hit 'p' during recovery mode

**Describe the solution you'd like**
When playing through _Startmenu or in the Build, have a debug mode where if you activate debug mode, then in Learn Mode/Setup Seed you have an option to pick any scene you want, however many times you want.

**Comment by westonb7** [comment]
A debug menu has now been implemented into the start screen - changes can be found in the Seed_bugfixing branch.
