### ISSUE TITLE
Seed Encoding Issue

### ISSUE THREAD

**Issue by BradyHammond** [reputage/seedQuest#437]
- Seed 52BE1E391AF51C8794E37CD3FEC3054D1 gave 52BE1E391AF51C8794E37CD3FEC3050D0 upon completion of rehearsal & recall
- Seed 6C87DDE23A0F865E087A4DDF2A7A6077A gave 6C87DDE23A0F865E087A4DDF2A7A60370 upon completion of rehearsal & recall
- Seed D159F42FE7DEE8161FDEE3BEF50C63F93 gave D159F42FE7DEE8161FDEE3BEF50C63390 upon completion of rehearsal & recall

All of these seeds were checked in rehearsal and recall at least twice

**Comment by westonb7** [comment]
This appears to be an oversight with the menu screen manager - I'll keep investigating and get a fix for this working soon.

**Comment by westonb7** [comment]
This bug is now fixed - the fix can be found in the seed_bugfixing branch and in the interactable_ui_updates branch.
