### ISSUE TITLE
Interactable Select Material

### ISSUE THREAD

**Issue by cameronthughes** [reputage/seedQuest#451]
**Description**
When Interactable is selected (without selecting any options) the material switches to a broken Material. 

Also, when the interactle is next to be selected(in the interactle order) it auto defaults to a bad material.

**Comment by jasukim** [comment]
These interactables turn into a broken material if it is selected without selecting any options, as Cameron says. Perhaps it has something to do with the Selection X-Ray Shader? @michaelmendoza 

![image](https://user-images.githubusercontent.com/6446247/63985389-5d38ad00-ca84-11e9-9f92-1e9f1d7b4c76.png)

**Comment by michaelmendoza** [comment]
Fixed in Dev branch
