### ISSUE TITLE
Interactable Action Wheel Overlay UI Not Scaling

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#454]
**Description**
If you select any of the interactables during "Hide Key" mode, the UI Overlay does not scale to the entire screen if at full screen. See screenshot for details. 

Default monitor size - 2440 x 1440 
Resolution - 1920 x 1080
Graphics - Medium 
Full Screen 

**To Reproduce**
1. Start "Hide Key" and generate Hex Key.
2. Select the ordered sequence of worlds. 
3. Play first scene and click on first interactable. 
4. See error. 

**Expected Behavior**
UI Overlay scales to entire scene. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6446247/63961881-a0742b00-ca46-11e9-9054-4d14d11fc4af.png)

**Device Info (please complete the following information):**
 - OS: Win10
 - Version 0.2.7.0
 - Device: Desktop

**Comment by michaelmendoza** [comment]
Adjust to InteractableAction UI to work at wider aspect ratios. 
![Uploading Screen Shot 2019-08-30 at 3.30.55 PM.png…]()
