### ISSUE TITLE
Pause Menu - Include Back to Main Menu, See Current Lineup

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#456]
P2- When selecting the Menu Button on the bar, it would be useful to have an option that leads the User back to the main menu to either hide/learn key or view the tutorial again. 

P3 - Would be good to show whether user is in Hide key/Find Key mode in Pause Menu, or in Main Bar? 

P3- It'd also be nice during Hide Key mode to have an option to see the current action lineup (eventually, maybe even the entire action lineup?) in the Pause Menu

**Comment by andreamorales** [comment]
I did make two different menus, 1 for the main screen, and one for when you're hiding or finding key. I think we probably need to implement both + add the changes that you talked about in your second issues.

**Comment by westonb7** [comment]
I re-added the "Main Menu" button to the pause screen prefab - -there were a number of bugs that made it problematic to restart from the pause menu, but I've fixed most of them now. There are still some visual bugs that I'll keep working on in the mean time. 
Changes made in the "Start_menu_updates" branch.
<img width="667" alt="Screen Shot 2019-09-03 at 11 51 26 AM" src="https://user-images.githubusercontent.com/30869523/64196478-2f1aea80-ce41-11e9-9c12-24e4483b6278.png">

**Comment by michaelmendoza** [comment]
Instead of having two menus. It probably be better to a single prefab. And had a code option to swtich beween the versions

**Comment by jasukim** [comment]
Seems like Andrea's working on putting in the UI to tell the player which mode they are currently playing (Hide/Learn Key), and Weston fixed being able to access back to menu screen. 

Created a new issue of adding in action lineup into Pause Menu screen here: https://github.com/reputage/seedQuest/issues/493

Closing issue as a result.
