### ISSUE TITLE
Plants in Start Screen are not scaling

### ISSUE THREAD

**Issue by andreamorales** [reputage/seedQuest#459]
**Description**
The plant illustrations in the start screen are not scaling in the game, which leave a blank space between them and the blue bar at the bottom of the screen.

**To Reproduce**
1. Start game.

**Expected Behavior**
The plants' bottoms should be touching the blue bar at the bottom of the screen.

**Screenshots**
<img width="1680" alt="Screen Shot 2019-08-29 at 4 30 55 PM" src="https://user-images.githubusercontent.com/21376359/63974229-6b81cb80-ca7a-11e9-8733-c005acedc925.png">

**Device Info (please complete the following information):**
 - OS: OS Mojave, v.  10.14.6, full screen

**Comment by westonb7** [comment]
This should now be fixed in the "Start_menu_updates" branch
