### ISSUE TITLE
"Menu" and "Help" buttons highlight to orange upon hover

### ISSUE THREAD

**Issue by andreamorales** [reputage/seedQuest#462]
**Description**
The "Menu" and "Help" buttons in the menu highlight to an orange color upon hover, when they should highlight to "#3A97D6".

**To Reproduce**
1. Go to start screen.
2. Hover over "Menu" or "Help" in top bar menu.

**Expected Behavior**
Button text should highlight to "#3A97D6".

**Actual Behavior**
Button text highlights to orange color.

**Comment by westonb7** [comment]
I don't know if you're still working on this, but I made a quick fix to cause these two buttons to highlight to  #3A97D6 in the "Start_menu_updates" branch

**Comment by andreamorales** [comment]
Awesome! Tagging @michaelmendoza so he remembers to merge that into dev later.
