### ISSUE TITLE
"Skip Tutorial" doesn't work 

### ISSUE THREAD

**Issue by andreamorales** [reputage/seedQuest#465]
**Description**
"Skip Tutorial" button does not work in Tutorial.

**To Reproduce**
1. Go to Tutorial.
2. Click on "Skip Tutorial" in first welcome screen.

**Expected Behavior**
When user clicks, Tutorial should be exited.

**Device Info (please complete the following information):**
 - OS: OS Mojave.

**Comment by michaelmendoza** [comment]
Fixed tutorial skip button. In dev. (0.2.7.2)
