### ISSUE TITLE
Flower Pot interactable in Tutorial is pink

### ISSUE THREAD

**Issue by andreamorales** [reputage/seedQuest#466]
**Description**
Flower Pot interactable in Tutorial is bright pink / not showing textures.

**To Reproduce**
1. Go to Tutorial.
2. Click on "Next" until you're allowed to walk for the first time.

**Expected Behavior**
Flower Pot has the right texture.

**Device Info (please complete the following information):**
 - OS: OS Mojave

**Comment by jasukim** [comment]
I believe this should be fixed as it's related to this broken material bug, which Michael fixed. https://github.com/reputage/seedQuest/issues/451
