### ISSUE TITLE
Tutorial UI/UX Feedback Build 0.2.7.0

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#467]
Seedquest Tutorial Feedback for SQ build 0.2.7.0

- [x] (P1) First pin is not immediately viewable on screen, will need to bring camera back so that User can see the pin over the flower pot. (Fixed, not in 0.2.7.1 but it is fixed as of 8/30 - Jane)

![image](https://user-images.githubusercontent.com/6446247/63968472-a53fdb80-ca54-11e9-9e1e-c4868fccab6a.png)

- [x] (P2) For the Tutorial section that goes over Pins and Interactable Bubble, we will need the Tutorial Overlay again to prevent player from moving. Would also be helpful to point to the Interactable bubble in this overlay.
![image](https://user-images.githubusercontent.com/6446247/63976555-6d419400-ca66-11e9-9caf-ee4cce33f75c.png)

- [x] (P3)When we get to "Click the button that matches the object in the bubble" It would be nice to have it so that the dialogue moves down or the overlay gets lighter,  indicating that the player is able to move around again. 
![image](https://user-images.githubusercontent.com/6446247/63976665-abd74e80-ca66-11e9-990e-53c4e837c26c.png)

- [ ]  (P2) It'd be nice to **bold** key terms like Pin or Undo like in this screenshot. Would be helpful to also point at Undo button as well. 
![image](https://user-images.githubusercontent.com/6446247/63975032-e6d78300-ca62-11e9-9e46-d341b36fd2cc.png)

**Comment by andreamorales** [comment]
Want to mention that we still are not able to add bold text a la markup. @michaelmendoza this is not super necessary but would be a nice to have.
