### ISSUE TITLE
Tutorial Bugs SQ Build 0.2.7.0 - Can't move, Can't exit, Missing Preview Interactables..

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#468]
- [x] -!!! (Programming) Player cannot move in Tutorial after Hiding Key and starting Find Key - you can select all the objects, but the Player cannot click on the ground to move or use WASD. 

- [x] -!!! (Programming) When selecting Exit Tutorial after finishing tutorial, User cannot actually Exit and will have to quit the game. 

- [x] -!! (Programming/UX) Skip tutorial button does not work. (Also strange, since the User wanted to select Tutorial, but where are we skipping to in Tutorial Mode? Skip Tutorial works if User is forced to do Tutorial if it's their first time Hiding Key though @andreamorales )

- [x] ![image](https://user-images.githubusercontent.com/6446247/63963051-fa75f000-ca48-11e9-904c-f6b175956267.png)
- [x] - (programming) Looks like Preview Interactable for Pantry Bread does not show up. Pin also is positioned in a strange place. ((Fixed by Jane, it was just a interactable bug))

**Comment by jasukim** [comment]
Bugs present still in ver 0.2.7.1

**Comment by michaelmendoza** [comment]
- Fixed player movement. (Fixed by setting GameManager.State to play after going to recall mode in tutorial. )
- Fixed Skip tutorial button. 
- Fixed exiting tutorial

Should be fixed in dev. (0.2.7.2)
