### ISSUE TITLE
Investigate large file repo

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#47]
Investigate possible solutions for large file repos for the unity files and assets.
Github only allows files of 100MB or less, and many files used for unity will be much larger.
Currently, the project's files and assets can't be pushed to the github repo, because their file size is too large.

**Comment by michaelmendoza** [comment]
Think Git along with Git-LFS would a good way to go. Take a look at this https://www.youtube.com/watch?v=OLneiOqEoU8

**Comment by westonb7** [comment]
Thanks, I'll take a look when I have the time!
