### ISSUE TITLE
Action Wheel displays more labels (Lab - Research Desk)

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#471]
**Description**
When selecting an object (in our case, the Research Lab with the Cat images), the Action camera sometimes zooms in and shows other labels in the background. See Screenshot. 
![image](https://user-images.githubusercontent.com/6446247/63988217-076a0200-ca90-11e9-916b-6eae8957dd6d.png)

**To Reproduce**
1. Go to Hide Key, select all lab. 
2. Go to Research Desk
3. Click on it,

**Expected Behavior**
No labels in the distance where there are no interactables, only just the action wheel label you selected. 

**Device Info (please complete the following information):**
 - OS: Win10
 - Version 0.2.7.0

**Comment by michaelmendoza** [comment]
Fixed in dev branch
