### ISSUE TITLE
Numbers in scene selection menu are behaving oddly

### ISSUE THREAD

**Issue by andreamorales** [reputage/seedQuest#474]
**Description**
When you're in the selection screen, the numbers appear alright as long as there are no double selections. If a scene is selected twice, the first number on the button disappear and only the second one remains.

**To Reproduce**
1. Go to Hide Key or Find Key.
2. Go to Selection screen.
3. Select one screen six times.
4. Bug appears as only the number 6 being displayed.

**Expected Behavior**
All numbers of selected scenes appear on top of their respective buttons.

**Actual Behavior**
Only last number of scene with duplicated choices appears. Example: even if restaurant is chosen 6 times, only the number 6 appears on top.

**Screenshots**
<img width="710" alt="Screen Shot 2019-08-30 at 3 47 40 PM" src="https://user-images.githubusercontent.com/21376359/64047706-879a7100-cb3d-11e9-8c1f-fbeae2901b00.png">

**Device Info (please complete the following information):**
 - OS: Mac OS Mojave

**Comment by westonb7** [comment]
This should now be fixed in "Start_menu_updates" branch. Tested with seed 080000020080000020000008000002000.
