### ISSUE TITLE
Fast Recovery Not Implemented in Tutorial

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#477]
**Description**
When going through the tutorial, and when you practice finding the key, you are given a prompt to try out Fast Recovery by pressing "F". However, the "F" key does not work. If you do select the Fast Recovery button, it will take the player to fast recovery but does not have options enabled. See screenshot. 

![image](https://user-images.githubusercontent.com/6446247/64056693-1b723a00-cb4a-11e9-910a-a0706e701c84.png)

**To Reproduce**
1. Start Tutorial mode
2. Play through Tutorial until the prompt asks you to start Find Key, and suggests using Fast Recovery
3. Press "F' - It doesn't not Work. 
4. Press Fast Recovery button
5. See Error
. See error

**Device Info (please complete the following information):**
 - OS: Win10
 - Version 0.2.7.1

**Comment by michaelmendoza** [comment]
Fixed. Fast recovery functional in dev.
