### ISSUE TITLE
After I get my seed from "Find Key", Start Again screen leads to wrong loading screen

### ISSUE THREAD

**Issue by andreamorales** [reputage/seedQuest#481]
**Description**
After I finish recovering a key in Find Key mode, I get the option to try to do it again. When I click on the button, it leads me back to the Scene Selection screen. I can then click on any scenes I'd like. When I get to the loading screen, though, it loads the first set of screens I had selected before I recovered the key.

**To Reproduce**
1. Go to Find Key.
2. Click on any set A of scenes.
3. Play through all the scenes.
4. Get key output.
5. Click on button to try again.
6. Select set B of scenes different from set A.
7. See loading screen displaying set A instead of set B. Showing set B would be correct.

**Expected Behavior**
Set B should be displayed in new loading scene.

**Actual Behavior**
Set A is displayed.

**Device Info (please complete the following information):**
 - OS: Mac Mojave

**Comment by westonb7** [comment]
This has now been fixed in the "Start_menu_updates" branch
