### ISSUE TITLE
NPC material issues

### ISSUE THREAD

**Issue by andreamorales** [reputage/seedQuest#492]
**Description**
Some NPCs lack eyes or other materials in Mac. I'll put them here.

**In Restaurant**

- [x] Woman in interactable that changes the tablecloths has no eyes

<img width="538" alt="Screen Shot 2019-09-04 at 5 24 25 PM" src="https://user-images.githubusercontent.com/21376359/64292656-dcbcf500-cf38-11e9-9afa-f95b96ef254b.png">

- [x] Host interactable NPCs have no eyes

- [x] NPC sitting in main room (non interactable) has no eyes.

<img width="331" alt="Screen Shot 2019-09-04 at 5 24 19 PM" src="https://user-images.githubusercontent.com/21376359/64292669-e181a900-cf38-11e9-84b6-2e719104680d.png">

**In Witch Tower**

- [x] Grind Ingredients not showing up (completely or just show up without materials on them)

<img width="538" alt="Screen Shot 2019-09-04 at 5 25 23 PM" src="https://user-images.githubusercontent.com/21376359/64292719-0249fe80-cf39-11e9-9873-2d81d238ebe8.png">
<img width="539" alt="Screen Shot 2019-09-04 at 5 25 27 PM" src="https://user-images.githubusercontent.com/21376359/64292720-02e29500-cf39-11e9-9d00-7105ca53f816.png">
<img width="548" alt="Screen Shot 2019-09-04 at 5 25 30 PM" src="https://user-images.githubusercontent.com/21376359/64292723-04ac5880-cf39-11e9-83a9-810041b152f9.png">

- [x] Chicken model in Ball doesn't show up
<img width="562" alt="Screen Shot 2019-09-04 at 5 26 32 PM" src="https://user-images.githubusercontent.com/21376359/64292803-2c9bbc00-cf39-11e9-8c6f-0a03d2a9ca83.png">

- [x] Raven model is not showing up.
<img width="578" alt="Screen Shot 2019-09-04 at 5 27 16 PM" src="https://user-images.githubusercontent.com/21376359/64292836-42a97c80-cf39-11e9-96c0-971473e3391b.png">

**In Castle Beach**

- [x] Cap'n Rum photograph does not cover full frame of interactable "Nemesis"
<img width="565" alt="Screen Shot 2019-09-04 at 5 30 00 PM" src="https://user-images.githubusercontent.com/21376359/64293008-a469e680-cf39-11e9-93c3-3d29247ffe85.png">

**In Saloon**

- [x] Hat Guy NPC has no eyes
<img width="571" alt="Screen Shot 2019-09-04 at 5 30 46 PM" src="https://user-images.githubusercontent.com/21376359/64293079-de3aed00-cf39-11e9-8651-7643e8da27fd.png">

- [x] Poker players have no eyes (only Dogs option has eyes)
<img width="530" alt="Screen Shot 2019-09-04 at 5 31 28 PM" src="https://user-images.githubusercontent.com/21376359/64293091-e2670a80-cf39-11e9-839e-6abd549359b3.png">

- [x] Bartender has no eyes
<img width="580" alt="Screen Shot 2019-09-04 at 5 32 03 PM" src="https://user-images.githubusercontent.com/21376359/64293113-ef83f980-cf39-11e9-8205-9119a6714a18.png">

**In Arabia**

- [x] Choose Food interactable not showing the barrels in all options except "Apples"
<img width="952" alt="Screen Shot 2019-09-04 at 5 33 42 PM" src="https://user-images.githubusercontent.com/21376359/64293234-2ce88700-cf3a-11e9-9441-e38d4ccf76fb.png">
<img width="952" alt="Screen Shot 2019-09-04 at 5 33 47 PM" src="https://user-images.githubusercontent.com/21376359/64293236-2ce88700-cf3a-11e9-8535-b82a7479b98e.png">

**In Cliffs*

- [x] Camp gang human NPCs don't have eyes (only the dogs do)
<img width="540" alt="Screen Shot 2019-09-04 at 5 36 00 PM" src="https://user-images.githubusercontent.com/21376359/64293408-805ad500-cf3a-11e9-8d7c-81df92e63efd.png">

**In Lab**

- [x] Chicken egg doesn't look that different from Ostrich egg - both appear white
- [x] Baseball hat on monkey is cutting through monkey's head
<img width="569" alt="Screen Shot 2019-09-04 at 5 37 37 PM" src="https://user-images.githubusercontent.com/21376359/64293496-b4ce9100-cf3a-11e9-8d4a-ecae86a29555.png">

- [x] Cat head in Weird Jar is not showing up
<img width="560" alt="Screen Shot 2019-09-04 at 5 38 02 PM" src="https://user-images.githubusercontent.com/21376359/64293523-c3b54380-cf3a-11e9-85e5-40e63a92e908.png">

**Comment by jasukim** [comment]
Did all the things \o/
