### ISSUE TITLE
In Farm, Encrypt/Hide Key mode - Cannot progress from Pig Interactable

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#495]
**Description**
Using Key 8E54AF1ECAA01E3C85B47A1679D199ED2

During Encrypt/Hide Key mode, I would play through Farm once fine, then the second time it'll give me a prompt to select "Pigs - Fancy Tart" but I would not be able to select the Action, thus being blocked from continuing. 

Perhaps it is due to the Farm appearing right after the first Farm in Scene Lineup?

**To Reproduce**
1. Go to Encrypt Key
2. Use Key 8E54AF1ECAA01E3C85B47A1679D199ED2
3. Continue through scenes until the second time you come across Farm
4. Try to select the Pig Interactable and on "Fancy Tart" 
5. Game does not register that action and does not allow you to continue. 

**Device Info (please complete the following information):**
 - OS: Win 10 
 - Version 0.2.7.4

**Comment by westonb7** [comment]
I've added some fixes that should now let the farm scene work properly, including a fix to auto-destroy the "interactable" component of a preview object. Changes made in a branch called "Interactable_preview_bugfix"
