### ISSUE TITLE
Can't Undo on World Selection Lineup

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#496]
**Description**
If a user selects a world in the World Selection screen for either Encrypt/Decrypt key, they are unable to undo the world that they've selected. 

**To Reproduce**
1. Go to Encrypt/Decrypt Key
2. Generate any Key
3. Select worlds 
4. U key does not work and no prompt to press undo 

**Expected Behavior**
An undo method is needed, whether that's an Undo Icon at a corner, or simply clicking on the world you need to undo, or dragging it off, etc. I think we mentioned options before.

**Comment by andreamorales** [comment]
@michaelmendoza this was supposed to work by adding the ability to drag worlds in and out of each of the slots. Can we still do that? I will still add an undo button.

**Comment by andreamorales** [comment]
Updated in update-HUD-design

**Comment by andreamorales** [comment]
@michaelmendoza we are still missing the dragging option though.
