### ISSUE TITLE
Encrypt Key - Should not be able to select any world besides pattern in World Selection

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#497]
**Description**
When in Encrypt Key mode, user should not be able to select any World besides the pattern in World Selection - but this is not the case. User can currently double click Worlds that are within a pattern which causes an incorrect sequence of Worlds during Encrypt Key mode. 

**To Reproduce**
1. Go to Encrypt Key
2. Use any key (try 007109E02F9CCEC493CA6E4F3372F55E8) 
3. User can select the first item (in ex, Cabin) multiple times to generate incorrect World sequence
4. User has incorrect scene lineup and will not learn the correct action lineup. 

**Expected Behavior**
In Encrypt Key, user should not be able to select any World in World Lineup more than needed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6446247/64381795-d71ee800-cfe8-11e9-99e6-fea6a69c483a.png)

**Device Info (please complete the following information):**
 - OS: Win10
 - Version 0.2.7.4

**Comment by westonb7** [comment]
Fixed in "Start_menu_updates" branch
