### ISSUE TITLE
Key Recovered "Try Again" Should Have Different Name/go to different function (backlog)

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#498]
**Description**
These are more UX notes. 

- [x] Encrypt/Hide/Learn Key - When a User reaches the end of their Encrypt Key mode and successfully recovers the seed, they are brought to a screen that shows their decrypted key and an option at the bottom to Practice Again. Upon selection, the user is sent to the Start Menu. It seems a little odd that if a User that intended to Practice is sent to the main menu, when they would be expecting to go to "Encrypt Key" mode or the "World Selection" menu. 

- [x] Encrypt Seed Recovery Would also benefit from having an extra option, so it's (Practice Again) (Main Menu) 

- [x] Decrypt/Find/Recover Key - When a user reaches the end of their Decrypt Key mode and successfully recovers the seed, they are brought to a screen that shows their decrypted key and an option at the bottom to Try Again. It might be good to have a caveat note here saying that it's possible that the user may have put the wrong actions in (would be great if user can review the Worlds and Action Lineup to check) and encourage the user to Try Again. 

Try Again sounds like it should lead the User back to the start of World Selection Screen though, and not the Main Menu. 

- [x] Also For Decrypt Key, Successful Recovery Window, perhaps we should have other option so we have an options lineup of (Try Again, Main Menu, or Exit SeedQuest)

**Comment by andreamorales** [comment]
On this!

**Comment by andreamorales** [comment]
Hey @michaelmendoza I can't for the life of me find the "Try Again" button screen. Here's what I had created 

<img width="702" alt="Screen Shot 2019-09-09 at 10 15 35 AM" src="https://user-images.githubusercontent.com/21376359/64538592-e6ed4380-d2ea-11e9-9ed6-79bd72303255.png">
<img width="661" alt="Screen Shot 2019-09-09 at 10 15 51 AM" src="https://user-images.githubusercontent.com/21376359/64538593-e6ed4380-d2ea-11e9-8ce3-b76cc2714dd9.png">

If you show me where the End Game screen is now, I'll make sure that it makes sense. My idea, @jasukim, was to always send the user back to the start screen, so there's no cognitive overload. I will, though, add the "Wrong key?  Here are possible reasons..." and a link to try again in text.

**Comment by andreamorales** [comment]
Completed all necessary changes in update-HUD-design. Only one was not possible - showing complete lineup of actions done, per our chat in Slack a month ago (that would be use cases 2 and 5). I agree that those use cases should eventually be a part of the user's experience, though. 

<img width="470" alt="Screen Shot 2019-09-09 at 3 02 46 PM" src="https://user-images.githubusercontent.com/21376359/64558943-1c0d8c00-d313-11e9-82b8-6a6c951ac688.png">
