### ISSUE TITLE
Typo with Ghost House

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuest#501]
**Description**
In the world selection and world lineup, there is a typo with Ghost House. 
![image](https://user-images.githubusercontent.com/6446247/64391184-beb8c880-cffc-11e9-99a6-1b2c3773f747.png)

**Comment by westonb7** [comment]
This typo has now been fixed ('Start_menu_updates' branch)
<img width="679" alt="Screen Shot 2019-09-06 at 11 38 15 AM" src="https://user-images.githubusercontent.com/30869523/64448432-ed857c00-d09a-11e9-9dfa-2700695df07a.png">
