### ISSUE TITLE
Font of each interactable label is wrong

### ISSUE THREAD

**Issue by andreamorales** [reputage/seedQuest#503]
**Description**
The correct interactable label font should be Rubik Bold. I know Michael said this was not doable yet because of the lack of the font's ability to have a shadow, but we should definitely at least try to, for now, change the font.

**Comment by andreamorales** [comment]
Bump :)

**Comment by michaelmendoza** [comment]
Message Received :)

**Comment by andreamorales** [comment]
Fixed it in update-HUD-design.
