### ISSUE TITLE
When recovering seed in fast recovery mode, bubble appears in Endgame UI

### ISSUE THREAD

**Issue by andreamorales** [reputage/seedQuest#504]
**Description**
I just finished recovering/finding/decrypting a key and I got this in the Endgame screen 

<img width="835" alt="Screen Shot 2019-09-09 at 1 59 23 PM" src="https://user-images.githubusercontent.com/21376359/64555257-ebc1ef80-d30a-11e9-9543-65d24f0717b2.png">

The bubble shouldn't be there.

**Comment by westonb7** [comment]
This has now been fixed in the "Start_menu_updates" branch
