### ISSUE TITLE
Missing/pink materials for some objects

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#517]
**Description**
We fixed almost all of these problems, however there's still a few objects here and there with missing materials, and show up as bright pink. I thought there was a list in the SeedQuest Planning spreadsheet doc for these, but I couldn't find it, so I'll list any I find here!

- [x] Venus flytrap variant of potted plant interactable in campgrounds scene (looks like it's just the leaves)
<img width="397" alt="Screen Shot 2019-09-18 at 9 57 55 AM" src="https://user-images.githubusercontent.com/30869523/65165470-1a6f5280-d9fc-11e9-8a74-609416b4a0ff.png">

- [x] News stand interactable preview in cafe scene. The interactable itself looks fine, it's only the preview that looks wrong
<img width="189" alt="Screen Shot 2019-09-18 at 10 08 16 AM" src="https://user-images.githubusercontent.com/30869523/65165624-6621fc00-d9fc-11e9-985c-a01d606a13ad.png">

- [x] fork on the default 'dessert' interactable in the cafe scene 
<img width="142" alt="Screen Shot 2019-09-18 at 10 11 16 AM" src="https://user-images.githubusercontent.com/30869523/65165828-c31db200-d9fc-11e9-9baa-4be485dd0744.png">

- [x] book on the table of the sleeping 'student' interactable of the cafe scene
<img width="351" alt="Screen Shot 2019-09-18 at 10 11 34 AM" src="https://user-images.githubusercontent.com/30869523/65165913-f19b8d00-d9fc-11e9-86d8-f20058f17f09.png">

- [x] Lantern for the "light source" interactable in the ghost house (only the default lantern though - all the interactable states have normal lanterns)
<img width="190" alt="Screen Shot 2019-09-18 at 10 35 29 AM" src="https://user-images.githubusercontent.com/30869523/65167715-51476780-da00-11e9-8076-7e0d5662e375.png">

- [x] Baseboard behind the 'bodega pet' in the ghost house
<img width="388" alt="Screen Shot 2019-09-18 at 10 35 49 AM" src="https://user-images.githubusercontent.com/30869523/65167764-69b78200-da00-11e9-932b-4deb8d090abd.png">

- [x] Eyes of the cat in the "Choose house guest" interactable of the ghost house
<img width="301" alt="Screen Shot 2019-09-18 at 10 41 40 AM" src="https://user-images.githubusercontent.com/30869523/65168101-0d089700-da01-11e9-93ef-4b584ba538f8.png">

- [x] Plant in the "hay" option of the trough interactable in castle beach scene
<img width="242" alt="Screen Shot 2019-09-18 at 10 46 43 AM" src="https://user-images.githubusercontent.com/30869523/65168427-bbacd780-da01-11e9-986f-d3e368eccc25.png">

- [x] I think the 'poison' option is supposed to look like this, but I'm going to put it in this list as a reminder to double-check it later
<img width="189" alt="Screen Shot 2019-09-18 at 10 46 54 AM" src="https://user-images.githubusercontent.com/30869523/65168496-e434d180-da01-11e9-96e8-7410434ce49d.png">

- [x] Eyes of the cat in the "Choose your king" interactable of the castle beach scene - probably the same material for the cat eyes for ghost house
<img width="189" alt="Screen Shot 2019-09-18 at 10 49 23 AM" src="https://user-images.githubusercontent.com/30869523/65168633-2f4ee480-da02-11e9-99dc-e230c126c193.png">

**Comment by westonb7** [comment]
As it turns out, the 'missing/pink material' issue is computer-dependent. The pink materials I see on my computer won't necessarily show up on someone else's computer, so I'm closing this since it's not relevant to anyone else at this time.

**Comment by michaelmendoza** [comment]
That would be mac dependant issue. You should keep this issue open until
fixed
