### ISSUE TITLE
Bug Log List

### ISSUE THREAD

**Issue by cameronthughes** [reputage/seedQuest#534]
The prefabs for the Arabian day merch's eyes are missing. Maybe be due to a material issue. 
![Screen Shot 2019-10-01 at 4 24 13 PM](https://user-images.githubusercontent.com/10523510/66008511-ae650380-e46b-11e9-82bf-eb1c89edd9ac.png)

**Comment by cameronthughes** [comment]
Treasure Chest transitions VFX too Large
![Screen Shot 2019-10-01 at 5 02 09 PM](https://user-images.githubusercontent.com/10523510/66008939-41526d80-e46d-11e9-8167-02dc401940d6.png)

**Comment by BradyHammond** [comment]
These have been corrected in my bug fixing branch.
