### ISSUE TITLE
Fast mode rotate on Cabin is off

### ISSUE THREAD

**Issue by SmithSamuelM** [reputage/seedQuest#543]
**Description**
Moving the rotation slider when in fast mode on the cabin scene rotates out of view

**Comment by michaelmendoza** [comment]
Which version of SeedQuest were you using @SmithSamuelM ? I believe this is fixed in version 0.2.9.0

**Comment by michaelmendoza** [comment]
This is will be fixed in v0.2.9.1

**Comment by SmithSamuelM** [comment]
Its version 2.9

**Comment by michaelmendoza** [comment]
Fixed in v0.2.9.1 release
