### ISSUE TITLE
Combine assets from assets-wip with scripts from dev branch

### ISSUE THREAD

**Issue by westonb7** [reputage/seedQuest#98]
Combine assets from assets-wip with scripts from dev branch

**Comment by michaelmendoza** [comment]
I'm working on making a project for this and transfering my side of things over to this with prefabs. I should be done with it soon.

**Comment by westonb7** [comment]
![screen shot 2018-06-11 at 1 04 19 pm](https://user-images.githubusercontent.com/30869523/41251700-fb6b3e2c-6d77-11e8-81ea-d8c8f4835baa.png)
Files have been imported into one project, still needs to be integrated.
